<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_I READ THE TERMS AND CONDITIONS</name>
   <tag></tag>
   <elementGuidId>56896dd2-fb58-43a7-a5a4-ec2f528c680b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i-read-terms-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i-read-terms-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28a66839-3403-4718-a21b-2d36b90b8810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67b5f846-5f48-4c3d-8ecd-9022fc362b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i-read-terms-btn</value>
      <webElementGuid>48f745f1-c7ed-4c21-af67-606a0c1136d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn mb-4 w-100 btn</value>
      <webElementGuid>b89f38ba-e0d0-4219-9bf4-d8d67a19a007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I READ THE TERMS AND CONDITIONS.</value>
      <webElementGuid>a6a5fcca-3539-4b95-a133-38a4451f49ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i-read-terms-btn&quot;)</value>
      <webElementGuid>4f21449e-bb33-495b-844c-d4466a7672b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='i-read-terms-btn']</value>
      <webElementGuid>9f90de83-9f25-4fe0-831d-05a03addbf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reviewFormAcceptTerms']/div/div/button</value>
      <webElementGuid>5a6bec91-0666-495f-82a1-2ecd1334fd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must read all terms and conditions to proceed.'])[1]/following::button[1]</value>
      <webElementGuid>d4b1190c-adc1-407d-983c-dac8970f059f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/following::button[1]</value>
      <webElementGuid>130f07f1-dcd4-4153-9191-8f0980cd3cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have read and agree to the terms and conditions.'])[1]/preceding::button[1]</value>
      <webElementGuid>d8a8e3e4-6e54-4723-a0a4-39dcafb066ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>cc13ac11-dedf-4bac-ade7-fe23d6e609b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'i-read-terms-btn' and (text() = 'I READ THE TERMS AND CONDITIONS.' or . = 'I READ THE TERMS AND CONDITIONS.')]</value>
      <webElementGuid>3ee1f923-bbbc-4fe3-8c25-a59d720ffd1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
