<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay Now</name>
   <tag></tag>
   <elementGuidId>01ae09cb-54db-422c-8164-ff3240a3ca25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pay-now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay-now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69fc6e1d-088e-44b3-a177-2f134668f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay-now</value>
      <webElementGuid>aa60cfae-def5-4328-a993-47028f6b4b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Get Protected</value>
      <webElementGuid>5fbc4fa7-d028-4b21-a752-90ee6f0009b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn mb-4 btn</value>
      <webElementGuid>8cc161c5-2208-4404-8635-d63b98c4de6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pay Now </value>
      <webElementGuid>5a3e5f88-7933-454c-bf2e-5ff69f10cd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay-now&quot;)</value>
      <webElementGuid>665319f4-5ca6-47d8-843f-a8f5b4670f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay-now']</value>
      <webElementGuid>ca66208a-1dfd-4523-be43-a04b340b201d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-summary/mdb-card/mdb-card-body/form/div[2]/button</value>
      <webElementGuid>32fe0fa5-2acf-4587-935e-a5f7a7f1179e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed: October 13, 2022'])[1]/following::button[1]</value>
      <webElementGuid>6f8a008c-1371-43da-82c4-7bb33cc90184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initials: tt'])[1]/following::button[1]</value>
      <webElementGuid>102e8176-c65e-40c9-b31d-0cd440f136ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::button[1]</value>
      <webElementGuid>316b46aa-d1a4-477b-b8c0-897240440081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8670cdba-2307-45d7-84e2-3ae0a1ea5905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay-now' and (text() = ' Pay Now ' or . = ' Pay Now ')]</value>
      <webElementGuid>250fa9fa-79a9-4169-a35d-7e3f43191208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
