<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_COMPLETE</name>
   <tag></tag>
   <elementGuidId>13c95006-8b61-4ae8-b4e7-8b3790e3a68f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-verification-complete-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='address-verification-complete-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfcfa469-d3d8-4b59-87dd-fcdfa48e21c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-verification-complete-btn</value>
      <webElementGuid>ad4cf081-c019-40c4-a9fa-fbc560dc642d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dbc178d4-4b70-494e-8309-d758b73f1145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn waves-light</value>
      <webElementGuid>bb58f613-8bff-427d-bede-05f74e4516dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMPLETE</value>
      <webElementGuid>1cc44f6d-cb57-4142-97dc-aaf0c4fca3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-verification-complete-btn&quot;)</value>
      <webElementGuid>b5440dd3-ff0a-468d-ab94-5fc96bad3436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0304602d-b339-4466-b6af-371a5de124bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-verification-complete-btn</value>
      <webElementGuid>94188070-c071-47b1-9762-673933f921be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>417d833e-4b48-4213-94f4-604f2b6ab2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn waves-light</value>
      <webElementGuid>34dc8bbe-d43c-4b72-88a4-e747f304cf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMPLETE</value>
      <webElementGuid>1b247f9d-66a4-46f1-a357-763ec614947d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-verification-complete-btn&quot;)</value>
      <webElementGuid>af4e3afb-bec4-4a63-a61d-7012aedb9aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='address-verification-complete-btn']</value>
      <webElementGuid>fd992bfb-3dd8-47a7-8218-451a4f862d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::button[1]</value>
      <webElementGuid>c6f76172-d756-4c5d-a1fc-da5e2d6d3d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Verification'])[1]/following::button[1]</value>
      <webElementGuid>52496664-e55a-403e-a2e2-1b46b88b8a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COMPLETE']/parent::*</value>
      <webElementGuid>50bae72f-aec0-4944-b641-a02edd99a87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>ba05fcbc-4828-478b-8668-e8b667f3e6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'address-verification-complete-btn' and @type = 'submit' and (text() = 'COMPLETE' or . = 'COMPLETE')]</value>
      <webElementGuid>b65428a2-ecb2-4175-94ad-bcaeaea4a2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
