<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name On Card_billingFormName</name>
   <tag></tag>
   <elementGuidId>f1195859-6fac-49b3-ae56-62854671d5c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingFormName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingFormName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1787df06-8ad1-457c-8cda-76b6d32a8367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bb78821-f4e5-4c98-8bd1-d642ca63a353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFormName</value>
      <webElementGuid>f16218fb-250e-4cd5-aa59-02d841a064de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cardName</value>
      <webElementGuid>1ef9aa36-0b32-4990-b717-60e7e17399b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b94d05d0-5e5d-4447-9907-110d2f9b371e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFormName&quot;)</value>
      <webElementGuid>bd034758-068b-4299-a974-ff26d23611cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0728a172-bd53-4cbe-9ed2-4ce6bbc0a7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8502e38-228a-4fdb-ae28-c6737bcceb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFormName</value>
      <webElementGuid>8e1cc0a3-d480-42af-a8b4-52ede581b8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cardName</value>
      <webElementGuid>6898b6e5-4052-42f4-9c08-25e5d842ce1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a15e9193-6d0f-479d-b8cd-1dfb90881adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFormName&quot;)</value>
      <webElementGuid>d597cbf1-f02b-449c-80af-b10e61043ea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingFormName']</value>
      <webElementGuid>ca69c15f-a2db-4581-93bf-602db7d27d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div/div[2]/div/input</value>
      <webElementGuid>113286e4-dfbf-46f1-b7fc-3e4005440367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>49883b71-5960-4134-a9ae-fb6396f8ff81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingFormName']</value>
      <webElementGuid>2607bc79-b274-4b87-9d6a-4aa031c9e14b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
