<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_January February March April May Jun_0a059c</name>
   <tag></tag>
   <elementGuidId>ba1aff49-43e3-4926-a050-f6d2d354d408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expoDateMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expoDateMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b2d04db-658f-4803-9109-b8c174d423d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ad9f7477-e0ce-438c-8d4b-a28e0d355aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expoDateMonth</value>
      <webElementGuid>8a647896-c6a5-4ede-b66b-8e5129af90e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exp Month *</value>
      <webElementGuid>c3c0276c-f728-492b-926e-dbc0b287e746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expirationMonth</value>
      <webElementGuid>2cdc747b-0e25-4b71-a0e7-bec5e5019949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>fa3b9585-c591-4f13-90b0-adb5d4aac881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  January February March April May June July August September October November December</value>
      <webElementGuid>e5d269be-841c-47de-a75d-aa2e2b589a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expoDateMonth&quot;)</value>
      <webElementGuid>82a5c09a-96ac-440b-8c0f-acda2b34db96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>70e9c392-80cf-4505-8a7d-f004b8088db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>dfa12282-e4b6-4fb3-b208-2d97750b6833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expoDateMonth</value>
      <webElementGuid>72140998-3184-4e46-b8f0-251a1a49de8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exp Month *</value>
      <webElementGuid>f2ed518d-42e7-4f9b-b86c-0a0b0625967d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expirationMonth</value>
      <webElementGuid>7a687026-d984-4126-b090-6fdc046a51bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>859cd474-1c88-4d30-ad72-c42ad4fb89f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  January February March April May June July August September October November December</value>
      <webElementGuid>bb41ac57-af17-414a-a665-96b00fc0a7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expoDateMonth&quot;)</value>
      <webElementGuid>c4cc1452-5cfb-4141-8f82-b2864fdc21bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expoDateMonth']</value>
      <webElementGuid>ec38e5ae-1e8e-4640-8536-12aca1912080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[3]/div/div/select</value>
      <webElementGuid>a8d6511d-f1ca-48e0-81d5-97161ccb0dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Month'])[1]/following::select[1]</value>
      <webElementGuid>c0a04efc-dddd-43b6-8cff-4a32aca33b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/following::select[1]</value>
      <webElementGuid>8d051d61-ee85-4cc0-ab03-01c8b6f75dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Year'])[1]/preceding::select[1]</value>
      <webElementGuid>1a16307d-3c62-47d2-a072-21cd9e9fbaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVC'])[1]/preceding::select[2]</value>
      <webElementGuid>c9c13b7b-3cc5-4ce8-b54c-e4712ad62dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>85576c56-394a-42c2-9383-313e30e8c501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expoDateMonth' and @placeholder = 'Exp Month *' and (text() = '  January February March April May June July August September October November December' or . = '  January February March April May June July August September October November December')]</value>
      <webElementGuid>206b6957-4ec1-4ecd-82b3-b829c7df2d60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
