<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Your Email_emailFormConfirm</name>
   <tag></tag>
   <elementGuidId>7e095187-6bd7-4ec2-9b09-09ba40b0b738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailFormConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1cba583-e001-4c42-87a0-bfa43d5f2062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>202d17ce-1e27-4517-bcb7-a1104e7eb52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormConfirm</value>
      <webElementGuid>dc827ae3-1f50-435b-9e9d-1ff763340278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>9cdee9e0-46d8-43e3-ac46-e895ee3e0cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c190-23 validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5e35557e-b177-4a55-a3ef-1a0e7af77dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormConfirm&quot;)</value>
      <webElementGuid>e6ba18f9-94d0-48b7-a52f-07a85b3748b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormConfirm']</value>
      <webElementGuid>09d7cacd-d1b3-4fcc-8e2e-6c8f00aeeea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[3]/div/div/input</value>
      <webElementGuid>b4535a95-605e-4acf-b9a6-cc4d4f6c1e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>af9e91e8-c3ce-40ad-8711-d81ea0425e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailFormConfirm']</value>
      <webElementGuid>087ea828-5b3b-4152-af86-4b59f10230ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
