<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_4 YEARS, 100,000 MILES  5 YEARS, 60,_d72163</name>
   <tag></tag>
   <elementGuidId>934c410d-80af-42ac-ac4a-04d4dec556fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='terms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e13ff7f5-f691-41f3-af58-fd6d7e7b649c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>05366b00-9f3e-48d0-a61e-51eaad62d1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>termlength</value>
      <webElementGuid>3b341fbc-61b7-4a04-ba3d-86e02caaca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>b13a3bac-6c99-4950-a1bf-84047bf6ab67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>b4659383-c81b-4cc5-b1bc-efb4390bb4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4840611f-8c13-4bc6-9e47-07ad3a6f3758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 4 YEARS, 100,000 MILES  5 YEARS, 60,000 MILES  5 YEARS, 75,000 MILES  5 YEARS, 100,000 MILES  6 YEARS, 60,000 MILES  6 YEARS, 72,000 MILES  6 YEARS, 85,000 MILES  6 YEARS, 100,000 MILES  6 YEARS, 120,000 MILES  7 YEARS, 70,000 MILES  7 YEARS, 100,000 MILES  7 YEARS, 120,000 MILES  8 YEARS, 80,000 MILES  8 YEARS, 100,000 MILES  8 YEARS, 120,000 MILES  10 YEARS, 100,000 MILES  10 YEARS, 120,000 MILES </value>
      <webElementGuid>59811833-e5ae-4c90-b78a-6633dcec14b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)</value>
      <webElementGuid>317884b8-a791-4b3f-8e17-ffdcba3c9698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='terms']</value>
      <webElementGuid>13e8355c-d5e8-4b00-9c6d-b17b2a250915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[2]/div/app-slice-product-tabset/div[2]/div/app-coverage-select/div/div/div/div/form/div/div/div/div/div/div/select</value>
      <webElementGuid>6717b130-e4bd-42d6-b7e9-ffe267cfe34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Your Term Length**'])[1]/following::select[1]</value>
      <webElementGuid>0156bd3e-d4ea-485d-8cba-1f5d3f73b05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payment Options'])[1]/following::select[1]</value>
      <webElementGuid>0b715a15-0037-423d-8952-6a415ce75a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payment Options'])[2]/preceding::select[1]</value>
      <webElementGuid>83024bc6-7c6e-4b85-aa08-b7f299d5e098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold Coverage Overview'])[1]/preceding::select[1]</value>
      <webElementGuid>488e32c8-788a-4c61-a560-3267a7531efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a18ddc8e-1a62-4dae-a968-039b538de9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'terms' and (text() = ' 4 YEARS, 100,000 MILES  5 YEARS, 60,000 MILES  5 YEARS, 75,000 MILES  5 YEARS, 100,000 MILES  6 YEARS, 60,000 MILES  6 YEARS, 72,000 MILES  6 YEARS, 85,000 MILES  6 YEARS, 100,000 MILES  6 YEARS, 120,000 MILES  7 YEARS, 70,000 MILES  7 YEARS, 100,000 MILES  7 YEARS, 120,000 MILES  8 YEARS, 80,000 MILES  8 YEARS, 100,000 MILES  8 YEARS, 120,000 MILES  10 YEARS, 100,000 MILES  10 YEARS, 120,000 MILES ' or . = ' 4 YEARS, 100,000 MILES  5 YEARS, 60,000 MILES  5 YEARS, 75,000 MILES  5 YEARS, 100,000 MILES  6 YEARS, 60,000 MILES  6 YEARS, 72,000 MILES  6 YEARS, 85,000 MILES  6 YEARS, 100,000 MILES  6 YEARS, 120,000 MILES  7 YEARS, 70,000 MILES  7 YEARS, 100,000 MILES  7 YEARS, 120,000 MILES  8 YEARS, 80,000 MILES  8 YEARS, 100,000 MILES  8 YEARS, 120,000 MILES  10 YEARS, 100,000 MILES  10 YEARS, 120,000 MILES ')]</value>
      <webElementGuid>e3283c22-635f-4111-91e7-761e52d5c755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
