<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NoYes_lever</name>
   <tag></tag>
   <elementGuidId>3800201d-c3a0-4ce8-9e34-61468de8cb14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;plan-tab-id-1&quot;]/div[2]/div/div/div/div[2]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.lever</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7542f965-0b71-42ee-8255-3b23548f75de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lever</value>
      <webElementGuid>605c434d-d9fc-4e59-8dfa-29a8f852e461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-tab-id-0&quot;)/div[@class=&quot;col-12 mt-4 mb-4 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c49-1 ng-trigger ng-trigger-expandBody ng-star-inserted&quot;]/div[@class=&quot;switch success-switch pl-2 pt-2 pr-2 text-center ng-tns-c49-1&quot;]/div[2]/label[1]/span[@class=&quot;lever&quot;]</value>
      <webElementGuid>c8ae17d2-e331-4e6e-9ca2-a3be1f165c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='plan-tab-id-0']/div[2]/div/div/div/div[2]/label/span</value>
      <webElementGuid>3a16d48a-6fe3-4bd2-8991-79d775ffefcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>6c485086-f5f9-44d6-a22c-3c2b712dabf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
