<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Agreement and Exclusions</name>
   <tag></tag>
   <elementGuidId>46859228-2844-4291-930a-7b9fbf64b602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-view-sample-contract-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-view-sample-contract-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ceb3269-b067-492a-88f5-ffe9d82fb2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>6945ff51-8075-42dd-91f4-30d636db8e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f12bb3e-1b42-495f-a91a-e410a2e8f9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-view-sample-contract-btn</value>
      <webElementGuid>9265f7de-3507-409e-a694-610bf615241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-text</value>
      <webElementGuid>16e7db42-0d7b-4b28-9319-c1c4c808fd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Agreement and Exclusions</value>
      <webElementGuid>1bceedac-3376-4c8d-9917-8a38f1fcb4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-view-sample-contract-btn&quot;)</value>
      <webElementGuid>dafc8119-e5cc-4d72-9114-b1aed3a535b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-view-sample-contract-btn']</value>
      <webElementGuid>397ccc36-66f0-46a4-a61c-c63ac7c8b2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div/app-cart-items/div[2]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>85e6e2a2-3afd-424d-a773-5add14144c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Agreement and Exclusions')]</value>
      <webElementGuid>40becdab-4490-49ea-b375-a087ed234a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::a[1]</value>
      <webElementGuid>fa0400d7-270a-448e-bafd-7e6fca9fd206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Light Duty Commercial Use Coverage: Yes'])[1]/following::a[2]</value>
      <webElementGuid>2624fa4c-c38b-4fa6-a9bb-d570b96c8054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Options'])[1]/preceding::a[1]</value>
      <webElementGuid>5a3969d7-33a8-4e1f-a6c1-a4346d172872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage starts'])[1]/preceding::a[1]</value>
      <webElementGuid>cee02870-3001-4267-abec-b488378ae01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Agreement and Exclusions']/parent::*</value>
      <webElementGuid>95c397d1-8591-4663-aab8-dfcffb01203a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>004494fe-4d4f-4a77-8d13-952ef90dd44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cart-view-sample-contract-btn' and (text() = 'View Agreement and Exclusions' or . = 'View Agreement and Exclusions')]</value>
      <webElementGuid>a81f3a28-d107-4375-b473-5b8616c70432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
