<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Agreement and Exclusions_1</name>
   <tag></tag>
   <elementGuidId>3404418f-d997-4490-b702-7b30d11d6295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='view-sample-tc-checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#view-sample-tc-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c315bd5-9867-4d26-a01c-cd6f507042a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>9281f4d3-206b-43bc-965b-d2c7bb1f417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>acec8d2b-a90d-416a-8fe1-998ec30afda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-sample-tc-checkout</value>
      <webElementGuid>59237953-26aa-4b67-964d-b6a660eb775b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-footer-text click-text</value>
      <webElementGuid>bf33abb8-4e17-49d1-bd05-a72b383eec6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View Agreement and Exclusions</value>
      <webElementGuid>4667b424-dcdd-4801-b6bc-86d5472da9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-sample-tc-checkout&quot;)</value>
      <webElementGuid>14106155-ebbb-47ed-8b76-9d48980e25f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='view-sample-tc-checkout']</value>
      <webElementGuid>eb4fbe31-e4d8-48a8-9230-2d59609b434e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div[2]/app-checkout-cart/mdb-card/mdb-card-body/div[4]/div/div/div[2]/div/a</value>
      <webElementGuid>4cfb15c0-42a5-4a57-bf1c-1aa514dfe97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Agreement and Exclusions')]</value>
      <webElementGuid>9b4c419f-8397-4919-a88c-f792a15d97ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Light Duty Commercial Use Coverage: Yes'])[2]/following::a[1]</value>
      <webElementGuid>c142785d-9268-45a5-8469-26bf20eb7b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>167298f1-288f-4b8d-8e21-70cb7efa3659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotal'])[1]/preceding::a[1]</value>
      <webElementGuid>d2b58248-5acd-497a-a4f2-6d66393c9cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Agreement and Exclusions']/parent::*</value>
      <webElementGuid>bd4fb784-8708-477f-b26d-731164bb156b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>bed96012-1fae-4056-9c24-e5877456e5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'view-sample-tc-checkout' and (text() = ' View Agreement and Exclusions' or . = ' View Agreement and Exclusions')]</value>
      <webElementGuid>6347b021-24b3-44f0-b71c-a7362f2c9767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
