<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Powertrain</name>
   <tag></tag>
   <elementGuidId>89ba6b9c-b524-4dee-b9f4-721c462e9a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chose-plan-1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-1 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0894afb-93de-4c0e-9744-fb540757beb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Powertrain+</value>
      <webElementGuid>b8890c1a-2794-4cf9-955a-cd70f2f3ec0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-1&quot;)/div[1]</value>
      <webElementGuid>660101ea-bdcf-4a16-b70a-a546c2441e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-1']/div</value>
      <webElementGuid>f3c8892c-9d42-4176-bd14-11ea622ed9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::div[2]</value>
      <webElementGuid>314fd49d-2278-4c1c-9865-a12fb442bf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********013546'])[1]/following::div[19]</value>
      <webElementGuid>880fc4d1-17e1-4325-9cb1-9103b7d6bc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::div[4]</value>
      <webElementGuid>57abd9b6-3a80-4f92-b95e-ba5dda2cee74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Powertrain+']/parent::*</value>
      <webElementGuid>0e1e6769-b225-407b-a14a-6a6427dbae44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div</value>
      <webElementGuid>b1d3da19-b925-4bfd-b257-8febd86ee3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Powertrain+' or . = 'Powertrain+')]</value>
      <webElementGuid>afa95b50-eaf0-40db-8233-e6d8c40ada82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
