<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms and Conditions</name>
   <tag></tag>
   <elementGuidId>f4b2576c-0db0-4fc8-ab66-f656a4fe1b09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4 > a.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c8563f6-315c-4b8c-8289-c1d606fbc406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ffa6692-6cc0-494a-812a-51bb33dcb6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>9f69a4a1-b6ef-4607-968f-8c23f59d3481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0142970c-cc84-4890-9cb6-eb23ad9380f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Terms and Conditions (opens in a new tab)</value>
      <webElementGuid>37877fc1-74fa-4f7b-8bba-ed5a4915e75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/terms-and-conditions</value>
      <webElementGuid>ff4c5231-0f3b-4b2d-bc57-fa84598b701c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/terms-and-conditions</value>
      <webElementGuid>ac14055c-6364-4746-be25-a9f2c354f88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>5ac6e682-d85f-4e79-845e-8b0bb6002e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms and Conditions</value>
      <webElementGuid>d668121b-bf39-4408-9ff0-8a1b31dfe927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c157-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-footer[@class=&quot;ng-tns-c157-0&quot;]/app-footer-contact-us[@class=&quot;ng-star-inserted&quot;]/footer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;footer-copyright text-center p-4&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-8 row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>df8022e5-ad0f-4662-bf09-acafe082b6c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      <webElementGuid>11442905-009e-45d0-aa72-3924d7fcc3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms and Conditions')]</value>
      <webElementGuid>afaedfeb-a37c-4829-9c54-57e1c6523db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sales@nissanprotection.ca'])[1]/following::a[1]</value>
      <webElementGuid>100cabdb-f7c3-4f9a-99fd-fa010a085afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(855) 999-1857'])[3]/following::a[1]</value>
      <webElementGuid>04ac2b7b-18af-478b-ab83-1e7917038ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::a[1]</value>
      <webElementGuid>cc1f3ff3-1eed-4987-ba82-ff48c55c3a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::a[2]</value>
      <webElementGuid>854dc1b0-1a7d-47e7-96d3-e973b6d22e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terms and Conditions']/parent::*</value>
      <webElementGuid>c5672f46-e611-482c-978c-534223b538b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/terms-and-conditions')]</value>
      <webElementGuid>a58045cf-ac76-45ad-b031-6f7a75782c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>892be625-27e0-42bf-ab37-4eefb52a4728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/terms-and-conditions' and (text() = 'Terms and Conditions' or . = 'Terms and Conditions')]</value>
      <webElementGuid>691ca961-d72e-4532-ae63-af12947cc135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
