<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What if my vehicle is still under warranty</name>
   <tag></tag>
   <elementGuidId>6d7c06a1-0ebe-4a77-a072-002e4ed7c40e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mb-0 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-0']/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3b10eee-191f-467a-a1fb-4b664b563581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What if my vehicle is still under warranty?</value>
      <webElementGuid>0108e79d-6e9a-4138-9ee5-fffc0cb9b152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-0&quot;)/span[@class=&quot;mb-0&quot;]/div[1]</value>
      <webElementGuid>8d62e809-04ed-4bf6-bcc5-822507dfeefc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-0']/span/div</value>
      <webElementGuid>e1a1ff59-2aa3-4857-928f-c46c4641dc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have questions about One Protect VSP?'])[1]/following::div[9]</value>
      <webElementGuid>4361d34e-aa55-423a-a637-dcb0df996358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protection on the Road'])[1]/following::div[13]</value>
      <webElementGuid>c2852cd4-ba6e-4802-a7c8-94a603d77ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/div</value>
      <webElementGuid>e031a7c9-5746-4ed9-bba4-3becd99d0338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'What if my vehicle is still under warranty?' or . = 'What if my vehicle is still under warranty?')]</value>
      <webElementGuid>dc5ccdae-fec3-4bcc-88f1-6b48f52f1332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
