<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How does the Trip Interruption benefit work</name>
   <tag></tag>
   <elementGuidId>434bd401-4c69-4c81-8f93-2afa9a9b18f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdb-accordion-head-568</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mdb-accordion-head-568']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f59ecf29-79e3-4526-bcaa-c33f0bb79331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>5c315f65-027d-40e6-93ec-29c33e5ba156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdb-accordion-head-568</value>
      <webElementGuid>297a8a6c-ec46-4f19-b91c-5ab4cf3f42e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How does the Trip Interruption benefit work?</value>
      <webElementGuid>8a846f4b-a7b8-43e6-bc2c-aec1dffa1116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdb-accordion-head-568&quot;)</value>
      <webElementGuid>ee2feaec-3922-4026-a9ba-9eab3dde4636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mdb-accordion-head-568']</value>
      <webElementGuid>cf22d8b9-3cb4-41d2-b0fb-92c1fb44f8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[3]/div/app-slice-faq/div/div[2]/div/div/div/div/mdb-accordion/div/mdb-accordion-item[7]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>3cd64551-c763-4e94-a0ce-781e969848f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Agreement'])[3]/preceding::div[2]</value>
      <webElementGuid>dbfa6712-caed-4d74-86ba-e596894fa78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[7]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>74c36444-5ff7-4f4a-8351-d40e0e245967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mdb-accordion-head-568' and (text() = 'How does the Trip Interruption benefit work?' or . = 'How does the Trip Interruption benefit work?')]</value>
      <webElementGuid>354f0aa9-8ea7-4a6d-9378-b873a533dade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
