<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Where can I find more details on what is _04d02b</name>
   <tag></tag>
   <elementGuidId>f649dca7-398c-4e71-b67a-a26d3be40d9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faq-button-14 > i.mdb-accordion-indicator.rotate-icon.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-14']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>225970eb-3118-4c68-8a18-2dd6da350acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5188994f-2696-4130-b05f-9950d4094b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdb-accordion-indicator rotate-icon ng-star-inserted</value>
      <webElementGuid>80df9d57-77df-448e-8fe7-216624b6d130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-14&quot;)/i[@class=&quot;mdb-accordion-indicator rotate-icon ng-star-inserted&quot;]</value>
      <webElementGuid>15c52c5b-8a56-43e3-853f-d3da2bff58e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-14']/i</value>
      <webElementGuid>3fcfa91e-5d41-45e6-8d20-62233998fdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[9]/div/mdb-accordion-item-head/div/a/i</value>
      <webElementGuid>f180512f-f285-4a89-950e-58ba230bc0bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
