<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_cancellations help page</name>
   <tag></tag>
   <elementGuidId>5e77ea30-8467-4d6b-a64d-98f7e0c43e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faq-button-4 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>6ef343fd-7c42-498a-812e-7252df27505f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cancellations help page</value>
      <webElementGuid>58517646-d1d0-4e17-ac13-5fa0f8e3561e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-4&quot;)/strong[1]</value>
      <webElementGuid>87c751a4-4c35-4975-9963-220596b09503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-4']/strong</value>
      <webElementGuid>7c70a83b-87c8-414e-bf3d-5bebb60a5e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='claims help page'])[1]/following::strong[1]</value>
      <webElementGuid>e92cb47c-2d96-4a9b-89ff-a1f98c873718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cancellations help page']/parent::*</value>
      <webElementGuid>cef0bb4a-b240-4d1d-accb-c7b0fb4ea094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[3]/div/mdb-accordion-item-body/div/div/div/p/a/strong</value>
      <webElementGuid>1a340389-0e19-4952-9568-00c7938f7240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'cancellations help page' or . = 'cancellations help page')]</value>
      <webElementGuid>da832ec8-272c-4e3d-b7ec-7f1d37103943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
