<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Agreement and Exclusions_1</name>
   <tag></tag>
   <elementGuidId>108470cb-77ca-4ef9-a1dd-c7c028e19384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='view-sample-tc-checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#view-sample-tc-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c433f146-625a-4965-b1df-eebe561e094c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>109b05d7-1dc8-41f7-99e2-90d107b3f07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84cf34fc-37e2-4a2e-9309-9a1061bfb31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-sample-tc-checkout</value>
      <webElementGuid>8e988824-a8c2-4b9f-a0da-66c819669a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-footer-text click-text</value>
      <webElementGuid>80d92d50-706a-4d57-8f62-8aa5676d9f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View Agreement and Exclusions</value>
      <webElementGuid>02e664ce-7696-4ce8-8afb-098ec8301509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-sample-tc-checkout&quot;)</value>
      <webElementGuid>272bd1a8-d637-440f-ac52-4cc8e28542cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='view-sample-tc-checkout']</value>
      <webElementGuid>5c91cd07-3c44-4f43-a216-e0c68442fae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div[2]/app-checkout-cart/mdb-card/mdb-card-body/div[4]/div/div/div[2]/div/a</value>
      <webElementGuid>0bffcf12-c57f-4665-aca3-5c98b54901d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Agreement and Exclusions')]</value>
      <webElementGuid>43da8d2f-4c79-49a5-a5a9-d44de46aa736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,628.00'])[2]/following::a[1]</value>
      <webElementGuid>5dc91838-b7c3-4fd3-b86f-bc5635ef748b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Use Coverage:'])[1]/preceding::a[1]</value>
      <webElementGuid>e700fee4-92dd-49a2-b115-3f7738dce3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIGHT DUTY COMMERCIAL USE COVERAGE'])[1]/preceding::a[1]</value>
      <webElementGuid>0e9e6831-edb8-4930-b6b6-e4c2e075e7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Agreement and Exclusions']/parent::*</value>
      <webElementGuid>cd3ebbb0-242e-41a7-9cb8-084fb6c8be3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>7925357c-9893-44ab-b5fa-00379d8bec84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'view-sample-tc-checkout' and (text() = ' View Agreement and Exclusions' or . = ' View Agreement and Exclusions')]</value>
      <webElementGuid>0151521a-436a-40f5-9f3f-8c588fc58429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
