<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_I READ THE TERMS AND CONDITIONS</name>
   <tag></tag>
   <elementGuidId>fc16b426-48bb-4c57-9af0-d6de38e9f9dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i-read-terms-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i-read-terms-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb2c9920-8d72-4a98-b377-9fcbd59f9c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88611158-b51b-47b6-8b48-34de44427430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i-read-terms-btn</value>
      <webElementGuid>9f277272-56a6-4223-9324-5e7e5605ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn mb-4 w-100 btn</value>
      <webElementGuid>e7ce4803-4f24-41bf-9793-c43af5ed789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I READ THE TERMS AND CONDITIONS.</value>
      <webElementGuid>ac4d2bf1-e453-42ee-9c4b-b19bd47daa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i-read-terms-btn&quot;)</value>
      <webElementGuid>8a9c28a0-370f-4098-8553-5428a1eb0bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='i-read-terms-btn']</value>
      <webElementGuid>f04fc020-4db1-4543-9a1d-15d0d1b9cae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reviewFormAcceptTerms']/div/div/button</value>
      <webElementGuid>4ff10231-27c2-4136-a5e4-391c106fa315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must read all terms and conditions to proceed.'])[1]/following::button[1]</value>
      <webElementGuid>dd288d2c-378c-48ee-9d09-73e1b7ae4015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/following::button[1]</value>
      <webElementGuid>ca5ced97-7f8b-437f-b11f-d0d6f6476d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have read and agree to the terms and conditions.'])[1]/preceding::button[1]</value>
      <webElementGuid>d8ad9fa0-2a4c-49c6-8ab5-6f0b13be267c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>44f6995c-a044-4e8b-a3fd-87539840f497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'i-read-terms-btn' and (text() = 'I READ THE TERMS AND CONDITIONS.' or . = 'I READ THE TERMS AND CONDITIONS.')]</value>
      <webElementGuid>28b94623-a53f-4007-846a-e397f75947d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
