<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platinum</name>
   <tag></tag>
   <elementGuidId>dfaa4a0e-a6ce-4753-a2ec-b8faa24f70aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chose-plan-name-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-name-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c13bffbf-ca2a-4568-aae4-01b2f6e06066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chose-plan-name-0</value>
      <webElementGuid>fac04eda-3a35-4e57-b118-9678ddec5f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum</value>
      <webElementGuid>9ebab90e-b609-4ffa-8ccf-2d5a7e7ac267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-name-0&quot;)</value>
      <webElementGuid>4b03a5bd-099e-4e65-8d2e-52c2c6a32fa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-name-0']</value>
      <webElementGuid>a649dcc4-6d5b-4455-8718-2cbe0fa04456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-0']/div</value>
      <webElementGuid>bd153797-63e0-4e66-a811-ef7b5295a830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********019075'])[1]/following::div[17]</value>
      <webElementGuid>3fd06d63-6c9f-4650-b37f-80b7f94aab9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MDX'])[1]/following::div[18]</value>
      <webElementGuid>d1418f15-65b2-4f02-8582-99ab9f4c184e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powertrain+'])[1]/preceding::div[1]</value>
      <webElementGuid>cfa1f227-8147-49df-98ce-a5b9cfd59908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platinum']/parent::*</value>
      <webElementGuid>727ae95c-23f3-48e0-a8cf-7ca5cfc6c812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>cd9b4522-45f4-4ac8-b2df-add323a3940d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chose-plan-name-0' and (text() = 'Platinum' or . = 'Platinum')]</value>
      <webElementGuid>42c6e7fc-8738-413c-afbd-a7802c4731be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
