<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Your Email_emailFormConfirm</name>
   <tag></tag>
   <elementGuidId>cba3281d-404d-4f88-8df7-039823b3c55f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailFormConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37cbfa6c-8081-470c-9b3f-609e659cdbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d443def7-58b7-4826-8ccb-eb0f115ba680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormConfirm</value>
      <webElementGuid>6af1187a-9924-49f1-9203-037c89602425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>aa95fd79-e512-4901-b9eb-0630a7058275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c295-24 validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>734e5051-4655-4527-aec0-7c54bbe196d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>c77442d2-0d74-4353-bb16-0a76b1e6d8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormConfirm&quot;)</value>
      <webElementGuid>519884d2-7874-4695-a1dc-97069b19bb7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormConfirm']</value>
      <webElementGuid>89969025-e278-4086-b608-92590a89e686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[3]/div/div/input</value>
      <webElementGuid>b40a4790-f515-4bbf-b824-e5c53a473a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>dc41de5a-4fa3-4309-9a23-6b59710b4a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailFormConfirm']</value>
      <webElementGuid>2bb81d12-972b-4058-968e-1983edc2b9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
