<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View Payment Options</name>
   <tag></tag>
   <elementGuidId>d9c042e4-905b-4b1b-b289-829e576d60bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-to-cart-button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-cart-button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f72be43-3eab-425e-bb1b-e87e61f020d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View Payment Options </value>
      <webElementGuid>6fcbadd8-a517-4bbb-9c4a-2df49dcc547a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-button&quot;)/span[1]</value>
      <webElementGuid>e2040062-07e9-432f-b56c-593cb3f72731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-to-cart-button']/span</value>
      <webElementGuid>7fded847-dd44-4567-a781-96f486dbcacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Your Term Length**'])[1]/following::span[1]</value>
      <webElementGuid>3a7aea8d-99ca-44b9-b715-0b91eadda56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payment Options'])[1]/following::span[1]</value>
      <webElementGuid>1105e42b-49c6-4223-8f20-892c7dc36e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum Coverage'])[1]/preceding::span[1]</value>
      <webElementGuid>56bb44cf-1bf3-4f0a-ad87-3a9f4e5adfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Major Parts and Systems'])[1]/preceding::span[2]</value>
      <webElementGuid>03f107c6-a78b-4ca7-a50b-caf71e7b738e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>d6c2435a-4d39-4e48-a7b9-a61ac85ddbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' View Payment Options ' or . = ' View Payment Options ')]</value>
      <webElementGuid>ef423957-d102-4982-8e9f-cc89dd641def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
