<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agreement</name>
   <tag></tag>
   <elementGuidId>23a110e8-07af-44b0-ab83-e16881da3b97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.underline > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/app-product-home/div/div[5]/div/app-slice-content-block/div/section/div/div/div[2]/div/app-component-text/div/div/p/strong/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>796fa90d-a47b-43a7-8c61-4469037001dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sgidigital.cdn.prismic.io/sgidigital/d72661fb-e700-4a13-84ce-805fafdfd89c_VRVSCA-D2C_200918_Accessible_Sample.pdf</value>
      <webElementGuid>d997c7f1-5708-41cb-ae55-53843a1e0457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agreement</value>
      <webElementGuid>cf5d90c1-4982-4960-87ff-6b72e30dd6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c157-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-product-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;non-electric&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/app-slice-content-block[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-block-wrap&quot;]/section[1]/div[@class=&quot;row d-flex align-items-stretch&quot;]/div[@class=&quot;col-md col-12 content-feature ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cb-text mobile-margin&quot;]/app-component-text[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row pb-2&quot;]/div[@class=&quot;col-12&quot;]/p[1]/strong[1]/span[@class=&quot;underline&quot;]/a[1]</value>
      <webElementGuid>3f74a146-53d9-4733-91ec-7e742637b393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[5]/div/app-slice-content-block/div/section/div/div/div[2]/div/app-component-text/div/div/p/strong/span/a</value>
      <webElementGuid>4729ef74-e164-47db-bf10-6c1b4778687d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agreement')]</value>
      <webElementGuid>edcf33a3-4209-4a1e-abc7-bf6eddb2b2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnostics Coverage'])[1]/following::a[1]</value>
      <webElementGuid>1ff95df7-e26b-4fd0-ac8b-d25a6dbcc68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>233421bc-a5c6-47ed-928d-f5c8f40d7b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agreement']/parent::*</value>
      <webElementGuid>cd5952a9-dea1-4b4d-8545-7541d7b72e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sgidigital.cdn.prismic.io/sgidigital/d72661fb-e700-4a13-84ce-805fafdfd89c_VRVSCA-D2C_200918_Accessible_Sample.pdf')]</value>
      <webElementGuid>f87dad6b-6871-4ad5-bc08-bc01d8fb2936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/span/a</value>
      <webElementGuid>e69ba7e0-30e0-48a8-8c8c-095fa528cf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sgidigital.cdn.prismic.io/sgidigital/d72661fb-e700-4a13-84ce-805fafdfd89c_VRVSCA-D2C_200918_Accessible_Sample.pdf' and (text() = 'Agreement' or . = 'Agreement')]</value>
      <webElementGuid>321be563-e4e1-4b31-a121-30c5ede20744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
