<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get Your Price</name>
   <tag></tag>
   <elementGuidId>e2ba6769-b4cb-4b1a-837e-18411aa8320d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cta-button-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cta-button-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ffcba0b7-1b83-4cd1-a278-0218d5a6dad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77a6ef19-893d-442c-b3d9-6471df4ac1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>324cbf73-b8ed-40ad-a6ca-a816540e072a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn cta-button mb-4 primary-btn</value>
      <webElementGuid>feb480ed-4b13-427a-b4ae-40a3063ff9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cta-button-0</value>
      <webElementGuid>a0ba7798-c15c-42c7-b24d-11f5f7845232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Your Price</value>
      <webElementGuid>83db2d73-5403-4bdd-b6b9-d1817693a87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta-button-0&quot;)</value>
      <webElementGuid>957c7e41-986c-46b1-a831-a736b15fc13a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cta-button-0']</value>
      <webElementGuid>2845c9ad-a0fc-43c8-96fc-bc8be1d768ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[9]/div/app-slice-content-block/div/section/div/div/div/div/app-component-cta/div/a</value>
      <webElementGuid>02fd5be2-866e-4b3a-9dbb-e9a2ad2d8d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get Your Price')]</value>
      <webElementGuid>c89949ec-f4fc-4da0-8ffc-304ef17f84b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>3828fcf2-4ae0-4695-ad6c-270237225072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convenience'])[4]/following::a[1]</value>
      <webElementGuid>7ed72446-58d8-4762-89b1-9ad7874269e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>6f16b0ab-7543-4d4b-b4a7-f85631275ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(833) 951-0123'])[3]/preceding::a[2]</value>
      <webElementGuid>3b6778a4-d4d8-4763-bc84-b08d6be28d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-component-cta/div/a</value>
      <webElementGuid>04281c84-8b4b-483d-8720-a7f6c5b7ab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cta-button-0' and (text() = 'Get Your Price' or . = 'Get Your Price')]</value>
      <webElementGuid>f99c64e6-a414-43c3-99da-3ca8a9bc983c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
