<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What is included with Roadside Assistance</name>
   <tag></tag>
   <elementGuidId>fe75e389-102b-4223-8cba-02cd022264ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdb-accordion-head-901</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mdb-accordion-head-901']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b105d1a0-1700-4b03-a3e8-ac59269d455e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>c098aa4d-c2e7-424a-afa4-ba03e1b93a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdb-accordion-head-901</value>
      <webElementGuid>fab84410-5314-4661-b7dd-86bfbd72efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What is included with Roadside Assistance? </value>
      <webElementGuid>5efe8cd4-c57d-4457-98f9-9a3f4ec1ac61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdb-accordion-head-901&quot;)</value>
      <webElementGuid>868afa82-e7b2-4965-ae43-45c1f59b48b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mdb-accordion-head-901']</value>
      <webElementGuid>c8bf74cb-4bbb-4920-93d9-17837bb37748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[3]/div/app-slice-faq/div/div[2]/div/div/div/div/mdb-accordion/div/mdb-accordion-item[6]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>9522f352-3be1-4730-973a-d2d1c6b27980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Agreement'])[2]/following::div[2]</value>
      <webElementGuid>7f598424-2ce7-4a90-a479-aea208fba4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is not covered?'])[1]/following::div[5]</value>
      <webElementGuid>bb4d040c-870e-4621-8149-05a93ccdd3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[6]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>330c90ec-0b18-4735-befe-d4435b6c4ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mdb-accordion-head-901' and (text() = 'What is included with Roadside Assistance? ' or . = 'What is included with Roadside Assistance? ')]</value>
      <webElementGuid>ec5eb1ed-0b1c-4e14-a758-922c14c2f67e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
