<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_What is included with Rental Car coverage_a0bebb</name>
   <tag></tag>
   <elementGuidId>a02e6ef3-9cdd-4316-843e-26b91d4d2d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faq-button-12 > i.mdb-accordion-indicator.rotate-icon.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-12']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>21b42806-87cc-4e8c-987e-ade882404d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2fe7dd6-8eb1-475e-b3c8-124788a6c2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdb-accordion-indicator rotate-icon ng-star-inserted</value>
      <webElementGuid>e4c1203b-33ab-4b16-b1b1-0266da2238a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-12&quot;)/i[@class=&quot;mdb-accordion-indicator rotate-icon ng-star-inserted&quot;]</value>
      <webElementGuid>cf5187d8-2d1f-4153-9c18-c1dc4c2022cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-12']/i</value>
      <webElementGuid>322ceb69-967a-44a2-84df-7f203ba24fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[8]/div/mdb-accordion-item-head/div/a/i</value>
      <webElementGuid>c8415a55-a465-4398-9449-c1fe151ddf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
