<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Terms_and_conditions</name>
   <tag></tag>
   <elementGuidId>df3ceb26-b261-49cd-bec5-53adceb42fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i-read-terms-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i-read-terms-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f5ed0a5-794f-41b7-bf5c-7c51ea6d5dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52f5c0c1-cb0b-48de-a460-c619df82d103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i-read-terms-btn</value>
      <webElementGuid>2cb4a6ea-fa19-4c53-846e-504ad49dd1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn mb-4 w-100 btn</value>
      <webElementGuid>0325b907-cbbc-4681-b850-cb4d52328a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I read the terms and conditions.</value>
      <webElementGuid>78724da8-f532-4b47-b5c3-4deed233c644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i-read-terms-btn&quot;)</value>
      <webElementGuid>691f3676-21be-466c-b656-7f078e9eaa38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='i-read-terms-btn']</value>
      <webElementGuid>1e49df46-61a2-41f7-83fc-ce5d4f3bca8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reviewFormAcceptTerms']/div/div/button</value>
      <webElementGuid>64a32612-1f7e-4cea-a17e-a57428ba497e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must read all terms and conditions to proceed.'])[1]/following::button[1]</value>
      <webElementGuid>a8732f84-eeb7-4296-85d6-7cf861b8b1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/following::button[1]</value>
      <webElementGuid>e15e37c8-86f0-4784-b9a9-6e039b094a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have read and agree to the terms and conditions.'])[1]/preceding::button[1]</value>
      <webElementGuid>d07a6190-0385-4531-b674-5eb43add50d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>4343f285-78b6-4960-b347-b4cefff8d3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'i-read-terms-btn' and (text() = 'I read the terms and conditions.' or . = 'I read the terms and conditions.')]</value>
      <webElementGuid>df49cc77-85ec-4bd6-94ab-c13ada9b36f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
