<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platinum</name>
   <tag></tag>
   <elementGuidId>f9ceddf4-9739-447e-9792-b5ce335ce696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-plan-select/div/div/div/div/div[1]/div/div[text()='Platinum']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-0 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9e66f9e-8256-45f4-9d8f-53467209d534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum</value>
      <webElementGuid>1ad6d8db-6705-47dc-bb5a-ec65305c3cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-0&quot;)/div[1]</value>
      <webElementGuid>7d3b3a73-903f-4a07-8b48-35e4e0c45302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-0']/div</value>
      <webElementGuid>cad8ed9e-5ca8-4365-bbf7-0078c711816e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********020470'])[1]/following::div[17]</value>
      <webElementGuid>1d777566-2e2b-4267-8009-218e691d296e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A4'])[1]/following::div[18]</value>
      <webElementGuid>47ebdfc2-9814-4b1f-a26c-6d4d632a76fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powertrain+'])[1]/preceding::div[1]</value>
      <webElementGuid>37ea72a7-96a5-4e85-b1ab-f69d7b14ff1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platinum']/parent::*</value>
      <webElementGuid>aa492969-bd76-4f12-88a8-d0194542b1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>58b2d1d8-2043-46fa-a7b2-fe278d5321da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Platinum' or . = 'Platinum')]</value>
      <webElementGuid>3b6d60b4-218c-4c5f-9c8a-8f15db00c9ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
