<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Silver</name>
   <tag></tag>
   <elementGuidId>5e58ef92-f569-4cf1-9e8f-0a250ed242a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-plan-select/div/div/div/div/div[1]/div/div[text()='Silver']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
