<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number</name>
   <tag></tag>
   <elementGuidId>3182a4e6-f1fb-41ba-9dbf-d5b7dea60b7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingFormCardNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billingFormCardNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e768d79c-3193-4c90-a035-712a0c94b92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fe78e25-640e-451b-a501-734d9017a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFormCardNumber</value>
      <webElementGuid>bf252ff2-90c0-49ea-9aa2-b78e0b9f93ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>0a7d058a-2f9d-4f14-8054-fd3333adddbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8e30de61-3beb-4af8-94e6-062cb7e95b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFormCardNumber&quot;)</value>
      <webElementGuid>dc0896c3-835f-49d7-8cb9-ab17121a442b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingFormCardNumber']</value>
      <webElementGuid>f83bf101-35da-42f3-aefe-2d8c8d47d93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[2]/div/div/input</value>
      <webElementGuid>88ae7e7e-4ea9-45bf-8efe-35daec7bcb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>12e190c9-753b-40f3-85eb-9f79e022464b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingFormCardNumber']</value>
      <webElementGuid>b6c83e2b-0f4a-4728-9e19-04e797ea4d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
