<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month</name>
   <tag></tag>
   <elementGuidId>8503747c-fe1e-4a45-9371-3eeee5460a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expoDateMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expoDateMonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a52bfca1-6b15-4222-b632-42d5d094b148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>690a9c0f-c42c-414c-9667-bd4831b055df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expoDateMonth</value>
      <webElementGuid>40899fc0-12c6-4056-9436-4e586000e165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exp Month *</value>
      <webElementGuid>a9b2c284-b045-4451-89c5-821b20e1e7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expirationMonth</value>
      <webElementGuid>daa87855-7d04-40eb-a87b-2b568f0d8718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>23a46a8e-2102-4997-8a8f-8f50e7428905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  January February March April May June July August September October November December</value>
      <webElementGuid>afd3c87f-5ef0-4bc0-8dc6-9e598d391690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expoDateMonth&quot;)</value>
      <webElementGuid>a2f38aa6-1566-4f9b-86d8-f501d151f76b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expoDateMonth']</value>
      <webElementGuid>97cb92f8-f703-46db-a0d8-69d08e0ee9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[3]/div/div/select</value>
      <webElementGuid>598197af-7ab8-4c5c-99c8-b4a0c3ecbd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Month'])[1]/following::select[1]</value>
      <webElementGuid>7aa368da-7e1d-4756-8d5e-7c17fe405865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/following::select[1]</value>
      <webElementGuid>c5d4451e-c84f-4b43-89c8-0eef1a8d1949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Year'])[1]/preceding::select[1]</value>
      <webElementGuid>7cbaed52-7156-4eef-aa7a-688ca66d29da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVC'])[1]/preceding::select[2]</value>
      <webElementGuid>6edb11e4-f047-495b-b412-bfb0c050ebbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>50c86cb7-9e2a-4371-8011-e2a5f5ba523b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expoDateMonth' and @placeholder = 'Exp Month *' and (text() = '  January February March April May June July August September October November December' or . = '  January February March April May June July August September October November December')]</value>
      <webElementGuid>498e55fa-a80d-4af7-9e6f-f7333b4ca3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
