<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Vin_Error_Text</name>
   <tag></tag>
   <elementGuidId>4a3c6886-6996-47a7-81ff-062c3388bc7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainContent&quot;]/div/app-product-home/div[2]/div[1]/div/app-slice-content-block/div/section/div/div[1]/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div/div[2]/form/div[1]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
