<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW AGREEMENT  EXCLUSIONS</name>
   <tag></tag>
   <elementGuidId>cef39f47-5784-4c7c-8318-edb5c7d33f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-view-sample-contract-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-view-sample-contract-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7551cb60-a24e-495c-8835-d410057b8536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>2b660f61-37c9-4194-80cc-2c7f4401519d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1303367-06c0-4123-9e91-d6d2e1bcbf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-view-sample-contract-btn</value>
      <webElementGuid>1497d402-b7eb-4a77-b6d7-bfe16e57723a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-text</value>
      <webElementGuid>ffc582cd-3133-4c18-90ff-b304ad1fca44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW AGREEMENT &amp; EXCLUSIONS</value>
      <webElementGuid>354691d1-fbd4-490f-b359-2ec9945a06be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-view-sample-contract-btn&quot;)</value>
      <webElementGuid>d56c5c23-a6b7-484f-8575-3cd03485d997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-view-sample-contract-btn']</value>
      <webElementGuid>03583913-4fa1-451a-90dd-fb01dc8f879d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div/app-cart-items/div[2]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>d4930071-5ccf-4461-ae67-3ff160eab5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>5ac9b6a7-013b-498c-8b33-fb1826910047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMOVE'])[1]/following::a[1]</value>
      <webElementGuid>6635d4d3-e9d9-492c-a517-769b29ffb249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::a[2]</value>
      <webElementGuid>ffab1c5c-3751-4de2-8261-44dc7df3c671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='payment options'])[1]/preceding::a[1]</value>
      <webElementGuid>db71e703-f123-46f6-9695-3045aad354a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Starts'])[1]/preceding::a[1]</value>
      <webElementGuid>de1a163c-ad3c-4244-ad9d-6ca54680de37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW AGREEMENT &amp; EXCLUSIONS']/parent::*</value>
      <webElementGuid>83c6ccf1-4528-4574-b535-b6bdef91445f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>9bebcbfc-4feb-4648-8085-6a831c815cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cart-view-sample-contract-btn' and (text() = 'VIEW AGREEMENT &amp; EXCLUSIONS' or . = 'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>4aeda7c0-c416-4736-abbb-d345794448c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
