<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_emailFormPhone</name>
   <tag></tag>
   <elementGuidId>30cf9bb1-270d-49ed-b753-a19665693b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailFormPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5adf6ca5-ff17-41be-b0a7-72c115a0c38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9250c674-fd14-46a5-926c-3fd51a69f345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f1a5d2d5-416f-413a-92c1-f601a9827342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormPhone</value>
      <webElementGuid>b5b8cdac-10db-49ae-b1f2-cc03e2845195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>b01d2cde-2c63-4ebe-bfe0-df7435767684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1c9a04b8-d460-4b1e-805d-89da6ef456b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c170-24 validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bc9b01c3-a0c8-4797-b1b3-1886582e70df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormPhone&quot;)</value>
      <webElementGuid>f6b03897-32a7-4c97-81e8-76b542a9a3e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormPhone']</value>
      <webElementGuid>164a3ebb-eea8-4d9f-8a91-ac02141e120f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[4]/div/div/input</value>
      <webElementGuid>cdfae91b-7834-43b4-a97a-3921d2cc66ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>582f5059-cc9d-4c67-a508-7b002565ee4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'emailFormPhone']</value>
      <webElementGuid>23a3ec59-c6f5-48c4-b9df-33b72596240b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
