<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current mileage_editVehicleOdometerVIN</name>
   <tag></tag>
   <elementGuidId>c39272c2-f3d0-4173-a8a1-f841c16a8549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editVehicleOdometerVIN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editVehicleOdometerVIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1d17ff3-b28c-4154-8c6e-ffec9b7f6a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>odometerlabel</value>
      <webElementGuid>b54510fd-7f4b-4cc4-802a-122fd75ba5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>489bced2-1e2b-441d-b9f3-07b45e0eb164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>a74a32d7-7a97-4e90-af1f-534fa45f7b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>d71306f8-cfc1-450f-afdc-a230c41ca596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6d5ff796-068f-4091-bfb1-330f2e732bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editVehicleOdometerVIN&quot;)</value>
      <webElementGuid>529a985a-af72-4464-b7ce-ed84b6b9e66f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editVehicleOdometerVIN']</value>
      <webElementGuid>5f53f1c9-22f5-447b-81dc-840d5af605a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div/div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>457a7ddb-fa37-422e-8aef-f3fe7e08c758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ae72c20a-edb5-4bfd-ad36-5ce3bac98340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'editVehicleOdometerVIN']</value>
      <webElementGuid>5401d60e-da09-4d0f-b8a3-4d689a3bde83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
