<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Powertrain</name>
   <tag></tag>
   <elementGuidId>d84817dc-1f67-450a-aa3d-bb4751f92ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;chose-plan-name-0&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-name-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75819b6c-5fc4-4c84-a3e3-8c8c83ab3321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chose-plan-name-2</value>
      <webElementGuid>c2a63002-2b9c-43c7-b883-7382ca433533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum</value>
      <webElementGuid>8708d75a-829e-40c7-b97a-45fd965deef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-name-2&quot;)</value>
      <webElementGuid>c7b74c2a-02cc-4e96-b963-ff043e60eb35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-name-2']</value>
      <webElementGuid>f6b26460-1346-4aaf-8870-e0e87317ff69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-2']/div</value>
      <webElementGuid>035d40dc-63ca-4f13-adfc-5b357b3629d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silver'])[1]/following::div[2]</value>
      <webElementGuid>0bf2c65c-4f33-4d92-9f41-d2468b86b274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powertrain'])[1]/following::div[4]</value>
      <webElementGuid>0198bb81-7554-4a5e-96c5-1c49d99de761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::div[5]</value>
      <webElementGuid>2d8154b5-e202-4715-9ba6-cda054ddb721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platinum']/parent::*</value>
      <webElementGuid>a6d1b554-5ac8-4683-b167-d8f4d7fa6dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[3]/div</value>
      <webElementGuid>119fc0eb-e4be-40ad-aa58-611ad82ab1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chose-plan-name-2' and (text() = 'Platinum' or . = 'Platinum')]</value>
      <webElementGuid>ed03ae4c-440c-4822-892b-e2ed27f81cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
