<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_2023 2024 2025 2026 2027 2028 2029 2_d4b0be</name>
   <tag></tag>
   <elementGuidId>a8a61454-c23a-483d-8569-4322583f3dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expoDateYear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expoDateYear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b820e4c-7626-40ba-aaea-514d07c5117c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>d2e4891b-28c7-4082-9e74-b938771c1966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expoDateYear</value>
      <webElementGuid>9281fe04-f038-4976-af21-7aaff40670d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiration Year *</value>
      <webElementGuid>a8b5d728-485e-49cb-8f9d-fecf2dae9f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expirationYear</value>
      <webElementGuid>cc216564-f3a6-4ea9-8422-dcde1c275035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6c5e35a4-8822-46fb-93c3-8c770e6487a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>expirationYear</value>
      <webElementGuid>43259f88-eb2f-4533-aeb8-34e8059ac21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  2023 2024 2025 2026 2027 2028 2029 2030 2031 2032 2033 2034 2035 2036 2037 2038</value>
      <webElementGuid>17584406-e348-41aa-af3e-b733e4e9f8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expoDateYear&quot;)</value>
      <webElementGuid>9d7c07c6-b482-4da3-beac-20ccf7807655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expoDateYear']</value>
      <webElementGuid>484642e8-1dbe-4938-b9a1-97462bb8f2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/section/mdb-card-body/form/section/div[3]/div[2]/div/select</value>
      <webElementGuid>075bd2f8-e47f-481c-bb93-0432916afa3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Year'])[1]/following::select[1]</value>
      <webElementGuid>78fac494-e363-4e1b-acd5-947d624c314a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Month'])[1]/following::select[2]</value>
      <webElementGuid>92485f41-c46c-4c98-bfdf-c8fab5d63aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVC'])[1]/preceding::select[1]</value>
      <webElementGuid>c215b476-bd57-432c-9f74-005a5111a8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We accept (Visa, etc.)'])[1]/preceding::select[1]</value>
      <webElementGuid>9b347ded-d217-48a2-922e-da4850744240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>eb721b23-e9dd-45e6-9e38-bb8c57a8f85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expoDateYear' and @placeholder = 'Expiration Year *' and (text() = '  2023 2024 2025 2026 2027 2028 2029 2030 2031 2032 2033 2034 2035 2036 2037 2038' or . = '  2023 2024 2025 2026 2027 2028 2029 2030 2031 2032 2033 2034 2035 2036 2037 2038')]</value>
      <webElementGuid>d26bd445-003b-44f8-9ed0-01b343ba49ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
