<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_6 YEARS, 90,000 MILES 4 YEARS, 40,0_79a636</name>
   <tag></tag>
   <elementGuidId>15eec97e-e9c5-47d0-b3c6-a92aae38a2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;terms&quot;]/option[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>93bcfd1b-95ec-4b4e-a190-e5f59c7b1eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>30a8abce-bb50-450b-b499-fafe1079583e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>termlength</value>
      <webElementGuid>6229e9e5-b63b-44a4-acfc-b5c837be6499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>be68185d-0e29-473e-9a0a-06a893278a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>0da1cbde-215b-4bcf-a82b-d09172697156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4f35bbb7-e0c9-4e53-abb0-a8ca34c182b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>637385bc-e4e6-4573-8c55-78a723d20159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 3 YEARS, 60,000 MILES  4 YEARS, 40,000 MILES  4 YEARS, 48,000 MILES  4 YEARS, 60,000 MILES  4 YEARS, 80,000 MILES  5 YEARS, 50,000 MILES  5 YEARS, 60,000 MILES  5 YEARS, 75,000 MILES  5 YEARS, 100,000 MILES  6 YEARS, 60,000 MILES  6 YEARS, 72,000 MILES  6 YEARS, 90,000 MILES  6 YEARS, 100,000 MILES  7 YEARS, 56,000 MILES  7 YEARS, 70,000 MILES  7 YEARS, 84,000 MILES  7 YEARS, 100,000 MILES  8 YEARS, 80,000 MILES  8 YEARS, 100,000 MILES </value>
      <webElementGuid>7c0a8536-dcdf-4e52-a205-0004790451a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)</value>
      <webElementGuid>e0003a8d-6a38-442e-b165-d0e90e39e9cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='terms']</value>
      <webElementGuid>f2e23b30-2254-4284-899f-313b8748d116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[2]/div/app-slice-product-tabset/div[2]/div/app-coverage-select/div/div/div/div/form/div/div/div/div/div/div/select</value>
      <webElementGuid>e91e2d58-0daf-4819-85e8-7de470563539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Your Term Length**'])[1]/following::select[1]</value>
      <webElementGuid>a7003a72-1c64-4b11-82f6-cbb01d4aa56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payment Options'])[1]/following::select[1]</value>
      <webElementGuid>65833c9d-6e96-494f-899e-c3f69d808b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payment Options'])[2]/preceding::select[1]</value>
      <webElementGuid>fb1d4a9c-92f7-4220-92b2-3006de5fc403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum Coverage Overview'])[1]/preceding::select[1]</value>
      <webElementGuid>6e065e0c-9b30-40af-8f03-55a0f9698793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d167e4ae-d84e-4fa4-8377-fe09d3236af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'terms' and (text() = ' 3 YEARS, 60,000 MILES  4 YEARS, 40,000 MILES  4 YEARS, 48,000 MILES  4 YEARS, 60,000 MILES  4 YEARS, 80,000 MILES  5 YEARS, 50,000 MILES  5 YEARS, 60,000 MILES  5 YEARS, 75,000 MILES  5 YEARS, 100,000 MILES  6 YEARS, 60,000 MILES  6 YEARS, 72,000 MILES  6 YEARS, 90,000 MILES  6 YEARS, 100,000 MILES  7 YEARS, 56,000 MILES  7 YEARS, 70,000 MILES  7 YEARS, 84,000 MILES  7 YEARS, 100,000 MILES  8 YEARS, 80,000 MILES  8 YEARS, 100,000 MILES ' or . = ' 3 YEARS, 60,000 MILES  4 YEARS, 40,000 MILES  4 YEARS, 48,000 MILES  4 YEARS, 60,000 MILES  4 YEARS, 80,000 MILES  5 YEARS, 50,000 MILES  5 YEARS, 60,000 MILES  5 YEARS, 75,000 MILES  5 YEARS, 100,000 MILES  6 YEARS, 60,000 MILES  6 YEARS, 72,000 MILES  6 YEARS, 90,000 MILES  6 YEARS, 100,000 MILES  7 YEARS, 56,000 MILES  7 YEARS, 70,000 MILES  7 YEARS, 84,000 MILES  7 YEARS, 100,000 MILES  8 YEARS, 80,000 MILES  8 YEARS, 100,000 MILES ')]</value>
      <webElementGuid>f08425e3-d307-4171-895e-9fb98eadd7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
