<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Get Your Price</name>
   <tag></tag>
   <elementGuidId>eac60962-89b6-4d2d-96f7-8d670efa6ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modal-component-see-pricing-btn-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-component-see-pricing-btn-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>184b039f-6edb-4ff8-b92d-039a4b2105ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f008efa0-7ffd-4b54-a136-e39f10afc7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-component-see-pricing-btn btn primary-btn flat waves-light</value>
      <webElementGuid>e0b2e3f3-aada-48cd-ad5b-212bb04cfcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-component-see-pricing-btn-0</value>
      <webElementGuid>10e72289-5d3a-4ba7-a075-4aeacbd0ea56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Your Price </value>
      <webElementGuid>6eb33c39-e3f1-40b0-a64b-c58fbdcb936a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-component-see-pricing-btn-0&quot;)</value>
      <webElementGuid>b53f6004-7ba4-4211-bec1-6c5fc7a87253</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modal-component-see-pricing-btn-0']</value>
      <webElementGuid>7ba50fb7-4a6f-44e7-bf0a-456d4d162e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[3]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div[2]/div/div[3]/form/div[3]/div/button</value>
      <webElementGuid>7d8e6d55-2c8b-4c65-a0ad-efe3aea260f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your odometer.'])[1]/following::button[1]</value>
      <webElementGuid>7814252e-1c3b-45e7-81b5-5f8a35d377cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current mileage'])[1]/following::button[1]</value>
      <webElementGuid>0fef8b80-4330-4766-aec4-a8512b2a6a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>4c60d609-6d2e-4526-9bde-35e7865e0f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'modal-component-see-pricing-btn-0' and (text() = 'Get Your Price ' or . = 'Get Your Price ')]</value>
      <webElementGuid>4d7cf56a-ef15-49b6-bfb1-9c6895568490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
