<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_COMPLETE</name>
   <tag></tag>
   <elementGuidId>4a5b5dff-8f1f-4826-954f-7ae91e9a997b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='address-verification-complete-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-verification-complete-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f228b736-d03d-42cb-805e-3585cff9d403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-verification-complete-btn</value>
      <webElementGuid>8f93b0aa-2fdd-49ec-a4f6-0dc296e70473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d7ee73dd-c8d2-406a-8da2-9d306c8eeb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn waves-light</value>
      <webElementGuid>af4fd026-30af-4b60-8f85-6a980c7d7907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMPLETE</value>
      <webElementGuid>82ac2117-cee2-4532-9fd0-0727b3cfc748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-verification-complete-btn&quot;)</value>
      <webElementGuid>be906391-c62e-4328-ab07-2bab672f38d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='address-verification-complete-btn']</value>
      <webElementGuid>61c42560-86b0-48b7-871d-597b1ddb7f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::button[1]</value>
      <webElementGuid>a943c463-b45b-4735-b274-92869657c7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Verification'])[1]/following::button[1]</value>
      <webElementGuid>86c39e8c-2ddc-4d3d-a1c7-4a0f944a8e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COMPLETE']/parent::*</value>
      <webElementGuid>c78bbf1a-98d1-4f06-930b-81453f775fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>3c345394-5bf5-413f-ac04-9066ee51a002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'address-verification-complete-btn' and @type = 'submit' and (text() = 'COMPLETE' or . = 'COMPLETE')]</value>
      <webElementGuid>0b4fff09-f4c2-475e-9047-8bbf0f6c187f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
