<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platinum ECO</name>
   <tag></tag>
   <elementGuidId>7230abfd-0c0f-4eae-a9cc-89921068c75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chose-plan-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29ebc920-c6e5-4a82-a75c-95f745f45d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17e3050c-5dc6-4992-ab2d-6b6551f859f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plan-select ng-star-inserted</value>
      <webElementGuid>e1e466ce-358e-485b-aeb6-4af0ec9803df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chose-plan-1</value>
      <webElementGuid>dc231a2b-a170-4af6-b824-b281a8aa8990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum ECO</value>
      <webElementGuid>b5a0d452-77fd-4154-b532-fa8eaaf7ef03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-1&quot;)</value>
      <webElementGuid>b45071d3-dd5e-436d-9a5a-296b62292ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-1']</value>
      <webElementGuid>284c7b99-c45e-4b70-a685-0ca21b4d519b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[2]/div/app-slice-product-tabset/div/div/app-plan-select/div/div/div/div/div/div[2]</value>
      <webElementGuid>ee8ea2e0-ec0a-46a9-9d08-58cead68db95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::div[1]</value>
      <webElementGuid>6e95c21e-c811-4965-b5b3-c92cbf508b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********820103'])[1]/following::div[18]</value>
      <webElementGuid>cae6d618-05bf-4b74-8c0f-386a65e3985a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold'])[1]/preceding::div[2]</value>
      <webElementGuid>dd4decdf-6a72-415b-951c-37b9599fc9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]</value>
      <webElementGuid>03d973f4-fb50-46f8-a0e6-86b331645f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chose-plan-1' and (text() = 'Platinum ECO' or . = 'Platinum ECO')]</value>
      <webElementGuid>069fe426-d5b6-4311-8624-07d091653e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
