<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__registrationFormCity</name>
   <tag></tag>
   <elementGuidId>2d7bc7db-d7d5-4f11-b76d-0d8238037a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registrationFormCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registrationFormCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b7853e0-e48d-4cd8-91bc-e83b18826ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37cd3ea7-b850-42b9-9ec8-5957d818766b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registrationFormCity</value>
      <webElementGuid>7e8954ff-ddeb-4ea1-b287-ca20cf3fe9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>8c2718cf-d9d0-4789-afac-4f45d6947be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3556f101-6cde-4cd9-bb99-db27706742c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registrationFormCity&quot;)</value>
      <webElementGuid>7817b61c-7adb-42bc-a3d6-73a5545419ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registrationFormCity']</value>
      <webElementGuid>1dd2ba9f-6675-4df7-bed0-d340e17d1972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/app-checkout-registration-info/form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>d9f8c209-e939-43b9-92c1-fa5893d4ac7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>90ebe9f2-671e-42b7-8d97-b910cdf95605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'registrationFormCity']</value>
      <webElementGuid>0be35cad-0e93-4069-8edf-96b3d27b190f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
