<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pay Now</name>
   <tag></tag>
   <elementGuidId>99e6fa3a-43d9-400f-a020-6af983dad3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pay-now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay-now']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a06d2f6-781d-4625-98a4-d31b1b7fe506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay-now</value>
      <webElementGuid>58a3a11e-21b2-45ac-bb09-aac3522ba166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Get Protected</value>
      <webElementGuid>957e6b29-5134-4fdc-88d9-c2e59bdf2f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn mb-4 btn</value>
      <webElementGuid>28a2dcfc-0d17-4553-bfc6-2fe1d3265b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pay Now </value>
      <webElementGuid>a7581df2-25f8-4d62-9024-001e8d4a7aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay-now&quot;)</value>
      <webElementGuid>498d2fe4-ba79-4591-bcee-dc5670b85e8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay-now']</value>
      <webElementGuid>9379cc63-b293-4187-b21e-a0feb8a9d144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-summary/mdb-card/mdb-card-body/form/div[2]/button</value>
      <webElementGuid>d6205f18-2552-463e-a8b2-7755c5907610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed: June 27, 2022'])[1]/following::button[1]</value>
      <webElementGuid>9c5e708c-6952-48bb-8b09-be9fc7a4cc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initials: tt'])[1]/following::button[1]</value>
      <webElementGuid>dea0efb6-d477-44f0-bd9f-f27539e67e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::button[1]</value>
      <webElementGuid>27fe756c-d694-448d-b731-72132d695ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>ea74d493-8065-4301-a496-92f3749b2b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay-now' and (text() = ' Pay Now ' or . = ' Pay Now ')]</value>
      <webElementGuid>ae2ba0fd-e8a8-4746-8a89-f735e3723dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
