<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get Protected</name>
   <tag></tag>
   <elementGuidId>36d76e55-65d6-4207-ac7d-621786e7c8b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cta-button-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cta-button-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a655366-007a-4f1c-ab4c-208fcb05fc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e33d5e5-3e90-4e08-991d-f204f6d4acc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48f65392-a0b6-4462-b6be-31c3af2b3c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn cta-button mb-4 primary-btn</value>
      <webElementGuid>b83f38dc-25ba-41fb-b086-8d7f70dac6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cta-button-0</value>
      <webElementGuid>dbca7776-a166-4e95-88ca-1dbcc3dac2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Protected</value>
      <webElementGuid>178e699f-231b-44b1-a286-48526fba7ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta-button-0&quot;)</value>
      <webElementGuid>be809ada-87db-447e-8bc9-c3177c939d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cta-button-0']</value>
      <webElementGuid>8bad454c-076c-4dda-ad4b-5b50d65b4e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[4]/div/app-slice-content-block/div/section/div/div/div[5]/div/app-component-cta/div/a</value>
      <webElementGuid>70f4b4e7-a9c5-4f32-83af-8eb299838a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get Protected')]</value>
      <webElementGuid>bca43f52-c888-42f6-9f4a-ddc21fa578fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$619 - $731'])[1]/following::a[1]</value>
      <webElementGuid>68b9d0fc-0fc8-47ee-8ac3-e165052c6866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Benefits To Help Keep You Moving'])[1]/preceding::a[1]</value>
      <webElementGuid>135f7861-79db-4359-b535-59169fe8cf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roadside Assistance'])[1]/preceding::a[1]</value>
      <webElementGuid>001b0c2d-723b-418a-a5ec-3478c196dade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Protected']/parent::*</value>
      <webElementGuid>5e85a2de-7c7c-4d97-8ada-34617a409913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-component-cta/div/a</value>
      <webElementGuid>ed73ee95-4fe7-4e86-a70a-db6e07a3f698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cta-button-0' and (text() = 'Get Protected' or . = 'Get Protected')]</value>
      <webElementGuid>17908f15-c78c-441c-a2f7-f7823ec82fb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
