<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Your vehicle, , s exact mileag_7f1a92</name>
   <tag></tag>
   <elementGuidId>5e706892-0278-4067-aa53-cc9e12c79c12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editVehicleOdometerVIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editVehicleOdometerVIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6d31778-0e01-4fa5-b3e4-79a631d2c627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>odometerlabel</value>
      <webElementGuid>acbf9019-4f8c-4e88-962e-2ef031f5a3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e34e8469-ed37-4006-930c-85119e614eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>4f97a0c3-8aaf-4ca0-8b69-105faf819601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>d1f4b67b-62ee-4425-9389-21e85f5f4da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7810c138-9350-4c64-a901-d914161c35b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editVehicleOdometerVIN&quot;)</value>
      <webElementGuid>92239af3-ea11-40d2-979e-476babf09a08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editVehicleOdometerVIN']</value>
      <webElementGuid>26a3dcbb-4a6e-4feb-899a-914bb9ed22ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div/div[2]/form/div[3]/div/input</value>
      <webElementGuid>241a57e0-b28d-47bb-9f94-f14a3fc8dc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>19f56b45-0dd7-4bd5-957e-f9256f710fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'editVehicleOdometerVIN']</value>
      <webElementGuid>3424b333-8883-493e-8cd5-90350776cd7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
