<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Terms_and_conditions</name>
   <tag></tag>
   <elementGuidId>5208a19e-f7f9-4638-9fbb-1a172f7cfbf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i-read-terms-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i-read-terms-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fe321707-c06e-4c4c-9372-06fae042375b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf786531-e551-4fbe-80e5-e0988d71c536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i-read-terms-btn</value>
      <webElementGuid>bdb553bc-a71d-4c29-9327-6f667ad78897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn mb-4 w-100 btn</value>
      <webElementGuid>56aeb47a-6bfb-4e1e-b9f9-3f02627ee9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I read the terms and conditions.</value>
      <webElementGuid>2eb5eb96-367f-43fc-8585-0f6152e56a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i-read-terms-btn&quot;)</value>
      <webElementGuid>0061c349-baee-4c3d-bae2-57083cd3f989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='i-read-terms-btn']</value>
      <webElementGuid>48159e44-835c-4018-a623-841d946d1476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reviewFormAcceptTerms']/div/div/button</value>
      <webElementGuid>a3b2e4d7-31f3-4480-aba2-c67f31b0709b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must read all terms and conditions to proceed.'])[1]/following::button[1]</value>
      <webElementGuid>68e75771-0d72-4689-9e0a-dbf0d91a9049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/following::button[1]</value>
      <webElementGuid>be84c4f7-0d8b-464a-999a-09f52cd5119b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I have read and agree to the terms and conditions.'])[1]/preceding::button[1]</value>
      <webElementGuid>f8dc0ca2-ba07-4d3c-bde9-73a6cfd0589b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>b2b11c2b-e55c-4f37-8032-f8031d7ca80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'i-read-terms-btn' and (text() = 'I read the terms and conditions.' or . = 'I read the terms and conditions.')]</value>
      <webElementGuid>bc4efbec-9a83-4ebe-a185-bd3f2350d3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
