<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platinum</name>
   <tag></tag>
   <elementGuidId>8eaa12b9-056a-4b9b-acf6-d169e4402cae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-0 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-plan-select/div/div/div/div/div[1]/div/div[text()='Platinum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51ad3937-a19e-4610-a347-e24f21abcb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum</value>
      <webElementGuid>82b976df-97ce-4681-a29a-4193c6e36a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-0&quot;)/div[1]</value>
      <webElementGuid>4aab03c6-a208-4fa5-9be1-a0987195f4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-0']/div</value>
      <webElementGuid>e62f37b1-1ad7-46c2-8bbf-152b74379a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********020470'])[1]/following::div[17]</value>
      <webElementGuid>5f67bf0f-299b-4c6c-80e3-80f1dd9bcf47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A4'])[1]/following::div[18]</value>
      <webElementGuid>1d7d5111-0413-43f0-ab22-0ec3740605f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powertrain+'])[1]/preceding::div[1]</value>
      <webElementGuid>1ab6d158-6505-4437-b4ad-5a4562841c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platinum']/parent::*</value>
      <webElementGuid>09beea3a-ced5-41f3-b9c1-f6fff78e553b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>8350a601-1868-4213-a774-1614834cf481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Platinum' or . = 'Platinum')]</value>
      <webElementGuid>20b0b21e-67e9-4ce0-bb53-df291d97c134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
