<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ConfirmEmail</name>
   <tag></tag>
   <elementGuidId>d29d6743-1d0c-4bd0-83d5-5fff19d0a267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailFormConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>060c9332-2da4-43d6-ab52-366522606561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>871e969f-7d98-4e2a-88f4-e99e36f73733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormConfirm</value>
      <webElementGuid>322d651d-94ef-4e59-90e6-c909d289bbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>1ca30e39-b989-4210-adca-1859400e077d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c169-9 validate-success validate-error ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>61af5f90-4cc8-4a7a-9eae-83c6acef51bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormConfirm&quot;)</value>
      <webElementGuid>93a08d4f-f198-433b-b3af-adf975c25746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormConfirm']</value>
      <webElementGuid>9dab1b93-9c52-49d5-bfe8-c161708e0166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[3]/div/div/input</value>
      <webElementGuid>a0c6a4e2-a85d-49fb-bb01-24530846c842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>f241fed7-e5e7-4ec5-9eb6-c5b6ee2f0acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailFormConfirm']</value>
      <webElementGuid>9b71e31c-3c24-436e-b787-3c4a6fe74bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
