<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number</name>
   <tag></tag>
   <elementGuidId>536fde02-be66-48db-98d6-85191032a744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingFormCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingFormCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b87bfca7-3d7b-4a16-98a5-b6c37c6b95bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>538f131f-6cce-41a2-97b8-e100c90dbb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFormCardNumber</value>
      <webElementGuid>5a836666-57c3-491f-9380-e2520efee522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>3b1ea9fe-cf4c-4cd6-a905-7f085332938f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b7344e80-7ace-4007-86f6-e2c7d2178052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFormCardNumber&quot;)</value>
      <webElementGuid>bb5c9d2c-048d-4d41-abf2-ee6be8ec5835</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingFormCardNumber']</value>
      <webElementGuid>ed7498e1-6bc8-491c-a0c8-767b3a51ffa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[2]/div/div/input</value>
      <webElementGuid>605d3e85-bce6-48ad-ba54-cd9b1a52af51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>2aab8da3-48b0-4338-96f7-9b9ef95feeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingFormCardNumber']</value>
      <webElementGuid>4bd08460-a371-450a-9b78-a029f3a7d433</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
