<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privacy</name>
   <tag></tag>
   <elementGuidId>8542f42a-6c02-4007-82ee-11d2348d34d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03b87b1a-3d3a-4a03-9b53-f42aa13a869f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a5c5638-c8ad-4f5e-9d62-a1dac5912f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>a80ffb5b-05a0-4e99-8f23-ba98e9198733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a0817ffd-b926-4966-88ed-ca34d11d7806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Privacy (opens in a new tab)</value>
      <webElementGuid>32b69256-43ec-48ee-8ef8-aa5b25af4a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/legal/privacy-policy</value>
      <webElementGuid>0283f3ac-1d94-4518-9d88-ec834a89d5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/legal/privacy-policy</value>
      <webElementGuid>dab153bd-9df4-4f22-a10c-5730d66ab98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>e7a9ce0a-1cad-4d20-9a25-73330974b454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy</value>
      <webElementGuid>eacb15f1-0118-4013-9b1f-65ce1fe3d099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c157-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-footer[@class=&quot;ng-tns-c157-0&quot;]/app-footer-contact-us[@class=&quot;ng-star-inserted&quot;]/footer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;footer-copyright text-center p-4&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-8 row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>4634667d-20fc-4430-83f1-4259468e2f92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>694566e0-03c7-4088-bafc-79b1fdf88fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privacy')]</value>
      <webElementGuid>9e9f8d6a-d818-41e6-ada5-e72c0db8febb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/following::a[1]</value>
      <webElementGuid>949323c4-abae-4f0d-95e8-6ef4f5d9ef5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@vroomprotect.com'])[1]/following::a[2]</value>
      <webElementGuid>710dc03e-d81a-4091-a2e9-a91cd81aa881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::a[1]</value>
      <webElementGuid>43f0130c-459b-4d71-8080-45dee330ea9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v 5.8.0'])[1]/preceding::a[2]</value>
      <webElementGuid>73c307a0-8a60-495c-ab97-f99f1f0445ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privacy']/parent::*</value>
      <webElementGuid>0c1c38fb-e7a2-4683-b295-1cb05f318495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/legal/privacy-policy')]</value>
      <webElementGuid>b4db0dfd-0a83-4835-aa9f-f6feea68e478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>1c249aaa-edd8-46bd-9950-352a7719f355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/legal/privacy-policy' and (text() = 'Privacy' or . = 'Privacy')]</value>
      <webElementGuid>ede1810f-9ea7-4fa2-b910-b7dd30d40928</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
