<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find My Price</name>
   <tag></tag>
   <elementGuidId>923e57b2-b5eb-4ba7-af4f-50dc6e52a653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.modal-component-see-pricing-btn.btn.primary-btn.waves-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecb241fb-3f37-456c-b368-1946f1e21283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d4ffda52-fee3-4a54-8b55-8a8a72f0c844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-component-see-pricing-btn btn primary-btn waves-light</value>
      <webElementGuid>c37638ba-af6a-4cf5-9cc7-e3207b9e94ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find My Price</value>
      <webElementGuid>4a48fe16-9723-401c-9f4b-580165ce0a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c164-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-product-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;non-electric&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[1]/app-slice-content-block[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-block-wrap gmc-main-hero&quot;]/section[1]/div[@class=&quot;row d-flex align-items-stretch&quot;]/div[@class=&quot;col-md col-12 content-feature content-feature-top-padding ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cb-text&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-component-vehicle[@class=&quot;desktop ng-star-inserted&quot;]/div[@class=&quot;row vehicle-info-container&quot;]/app-verify-vehicle[@class=&quot;verify_form ng-star-inserted&quot;]/div[@class=&quot;verify-vehicle ng-star-inserted&quot;]/div[@class=&quot;vehicle-edit ng-star-inserted&quot;]/div[2]/form[@class=&quot;no-OID-form ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row w-100 d-flex justify-content-center&quot;]/div[@class=&quot;col-12 text-center&quot;]/button[@class=&quot;modal-component-see-pricing-btn btn primary-btn waves-light&quot;]</value>
      <webElementGuid>f02c82a5-1f87-407d-8875-5a0772c34b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>8e1cf37a-f91f-4f0c-a53e-1096ca11a3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div/div[2]/form/div[5]/div/button</value>
      <webElementGuid>a6ed8d70-6f90-4187-a0ef-7e0966cc701d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State of Vehicle Registration'])[1]/following::button[1]</value>
      <webElementGuid>1b829a07-e697-4378-8ccc-7330b3f865dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Mileage'])[1]/following::button[1]</value>
      <webElementGuid>647f1d09-a9c7-4c7f-b3f4-60b857b06be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Protection Endorsed By GMC'])[1]/preceding::button[1]</value>
      <webElementGuid>4642c424-040f-47c7-8bec-651f52f2c6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>89e1c501-bd61-4578-b5f5-ab72b69bd78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Find My Price' or . = 'Find My Price')]</value>
      <webElementGuid>90791df4-e57a-46fb-aa38-3517ff1a744d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
