<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current Mileage_editVehicleOdometerVIN</name>
   <tag></tag>
   <elementGuidId>2c01ef41-0a0d-40a1-bfef-81ee32cc65bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editVehicleOdometerVIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editVehicleOdometerVIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e5eb562-272b-425c-9dc2-71f60f03a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>odometerlabel</value>
      <webElementGuid>b13752d1-27b4-4c77-b9a5-8cec6a0b920d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58510104-08d7-448c-ab04-0752d09925a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>1bffdc43-91fe-449e-a1a9-e685452a9558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>eff98a23-3b22-4064-af80-300e052afc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>1ecf6bc3-774b-41fd-a981-2963e75dd620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editVehicleOdometerVIN&quot;)</value>
      <webElementGuid>6dd88300-f5b6-4ffb-b8ae-5f9a068f114e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editVehicleOdometerVIN']</value>
      <webElementGuid>9d5061f4-7aba-41ad-83ed-20ac57662db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div/div[2]/form/div[3]/div/input</value>
      <webElementGuid>286bba14-4fe0-4264-aaae-33e1b33984ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9c21445b-055b-4e36-abd8-536cf91b4c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'editVehicleOdometerVIN']</value>
      <webElementGuid>e6a6f0d1-2555-4da8-bc61-ba354c784d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
