<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW AGREEMENT  EXCLUSIONS_1</name>
   <tag></tag>
   <elementGuidId>646ac87d-1638-409a-8ca4-2517866b385b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view-sample-tc-checkout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='view-sample-tc-checkout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a653719-cf7d-46ac-9759-c64a7f53dc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>cb75a241-fccc-43f3-87a2-064c5973f1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85d86bb1-fc33-4626-8d50-5bdabcf4b7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-sample-tc-checkout</value>
      <webElementGuid>9798f4d7-6c46-4f4e-a8ec-8364652a06ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-footer-text click-text</value>
      <webElementGuid>a3cf8971-0ad2-46ff-9b0a-6395f1ab132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW AGREEMENT &amp; EXCLUSIONS</value>
      <webElementGuid>ce2c195a-fd1d-41e0-806f-f87a6b16aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view-sample-tc-checkout&quot;)</value>
      <webElementGuid>aa69a22e-2966-4813-aa6b-f8021cca1f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='view-sample-tc-checkout']</value>
      <webElementGuid>01b0ee2f-28e7-471f-996c-d6332fb3f327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div[2]/app-checkout-cart/mdb-card/mdb-card-body/div[4]/div/div/div[2]/div/a</value>
      <webElementGuid>a2bf6eab-a8e4-4fb7-b889-5c5a15ed1cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>4c4a5f6c-cae3-4bc5-bea0-7962e16f3e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,990.16'])[2]/following::a[1]</value>
      <webElementGuid>61d9e87b-d630-4dc5-971d-587bdb0e70d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[2]/following::a[1]</value>
      <webElementGuid>56832764-8951-49da-ab9c-cd8ec7783b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT SUMMARY'])[1]/preceding::a[1]</value>
      <webElementGuid>80689ffc-0298-4f81-b0d5-0154d45b1050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBTOTAL'])[1]/preceding::a[1]</value>
      <webElementGuid>017c7b6b-d7ef-4664-92bd-f4322a7f5f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW AGREEMENT &amp; EXCLUSIONS']/parent::*</value>
      <webElementGuid>48dff082-5c44-4fc5-93a9-ea7cbcca0ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/a</value>
      <webElementGuid>c4348c3f-37c6-438a-97a8-4d7420f425e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'view-sample-tc-checkout' and (text() = 'VIEW AGREEMENT &amp; EXCLUSIONS' or . = 'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>83789166-8add-4388-96b7-cb4485c49d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
