<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW AGREEMENT  EXCLUSIONS</name>
   <tag></tag>
   <elementGuidId>4ac0c58c-1ea8-4ac8-af44-d98ad6e7f637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-view-sample-contract-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-view-sample-contract-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2b81557-f159-4273-9c5d-b0092a502545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>535e5c3d-1296-49db-b673-4fa8231b3e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>13373749-e2b6-4851-aa47-142022a854ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-view-sample-contract-btn</value>
      <webElementGuid>75cb73d5-0160-45d6-acd9-8a357801f18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-text</value>
      <webElementGuid>3f36995b-b13b-4f24-bbad-8749ae58b0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW AGREEMENT &amp; EXCLUSIONS</value>
      <webElementGuid>d730f762-ef65-40d0-ad53-76b5ea7c2d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-view-sample-contract-btn&quot;)</value>
      <webElementGuid>102ddd1f-7434-442d-9860-263d4a018af6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-view-sample-contract-btn']</value>
      <webElementGuid>1a6989f2-a8ec-49f6-89ad-61c318a05a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div/app-cart-items/div[2]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>8027ce0f-ff61-4081-b381-21fd3c417274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>0d619ac7-a59c-4067-9e04-91dae447caa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMOVE'])[1]/following::a[1]</value>
      <webElementGuid>ede84bd1-95d1-486f-968d-dd4ab792e246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::a[2]</value>
      <webElementGuid>ec361d2e-87e6-4308-abc6-cb3858107f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='payment options'])[1]/preceding::a[1]</value>
      <webElementGuid>3c911763-fbfd-496f-8c4a-492708c204bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Starts'])[1]/preceding::a[1]</value>
      <webElementGuid>6f270484-bac4-4864-a2b2-903510608001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW AGREEMENT &amp; EXCLUSIONS']/parent::*</value>
      <webElementGuid>19ca17d1-470f-44dc-bcb0-c09bf9730619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>12fb896d-fe37-4615-a573-efe4ed5fa1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cart-view-sample-contract-btn' and (text() = 'VIEW AGREEMENT &amp; EXCLUSIONS' or . = 'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>f24635b6-3f1f-4304-bd57-236f4fd34398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
