<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_emailFormPhone</name>
   <tag></tag>
   <elementGuidId>d819ecf5-e421-4f64-a548-0f13e07d940c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailFormPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b5fee6-a5e5-4e29-a1f0-ad1c17b4e0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afa8a0a4-32bf-4fb6-bb5b-bb192e566ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>876ecb8b-eabb-46f2-b4ff-5e7c67992d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormPhone</value>
      <webElementGuid>4bbc40d7-eba8-4a3d-ad5e-f733a20bb28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>0ed4d38f-db9d-4fa1-a00a-737e0f4351b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4808cb70-d919-49b2-8b81-29589f163c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c170-24 validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7234b6d0-17d5-44c6-879a-e795d54b0003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormPhone&quot;)</value>
      <webElementGuid>a4100084-b14d-4bca-9909-0d9a15e46d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormPhone']</value>
      <webElementGuid>700bd41c-6daa-4e84-9c7a-311a20b7a8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[4]/div/div/input</value>
      <webElementGuid>7fe2b2fe-b547-45ac-aa6a-740f0e142932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>1372a5d8-29d6-4576-bdc6-8a289794d011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'emailFormPhone']</value>
      <webElementGuid>f226310b-f9b8-42c5-b9e3-cd3e0cf6e31d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
