<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What if my vehicle is still under warranty</name>
   <tag></tag>
   <elementGuidId>ca7460d7-a5f0-4f49-97d6-7872c9ab5c01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mb-0 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-0']/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90dddfbf-c503-48eb-a806-e1164266a427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What if my vehicle is still under warranty?</value>
      <webElementGuid>c945c45a-ba90-4da9-9929-b0f7144fda4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-0&quot;)/span[@class=&quot;mb-0&quot;]/div[1]</value>
      <webElementGuid>6fbafba2-b6be-4c8d-af89-4806dc828cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-0']/span/div</value>
      <webElementGuid>13078987-adf3-43d5-8bbd-6a08f56a8121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have questions about One Protect VSP?'])[1]/following::div[9]</value>
      <webElementGuid>ae062175-062a-4f44-9477-7f9e56636bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protection on the Road'])[1]/following::div[13]</value>
      <webElementGuid>6ac9ce4a-3bf7-4400-ad22-5c928e530d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/div</value>
      <webElementGuid>c69c99f1-f597-4f01-9b5f-211d5ad974c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'What if my vehicle is still under warranty?' or . = 'What if my vehicle is still under warranty?')]</value>
      <webElementGuid>8e482dbc-9d90-4552-b1a4-adebca7fcddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
