<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How does the Trip Interruption benefit work</name>
   <tag></tag>
   <elementGuidId>f6914856-033e-4684-9c19-27756263b009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdb-accordion-head-568</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mdb-accordion-head-568']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e6b5264-5170-45bf-897d-06a84a54bb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>6e7f4919-cefd-4247-9a4c-cfa95aa712e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdb-accordion-head-568</value>
      <webElementGuid>5cd8f87b-7826-45a0-86a2-c21b2a3a305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How does the Trip Interruption benefit work?</value>
      <webElementGuid>a7be488f-bddf-4985-a79e-781d5472d38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdb-accordion-head-568&quot;)</value>
      <webElementGuid>44297e6e-e6d4-44e2-9e49-438cfed4baf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mdb-accordion-head-568']</value>
      <webElementGuid>5eee28ff-b10f-4c21-a6f9-7a298d77da9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[3]/div/app-slice-faq/div/div[2]/div/div/div/div/mdb-accordion/div/mdb-accordion-item[7]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>6d40722a-1523-48ed-a5f0-2bd159672be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Agreement'])[3]/preceding::div[2]</value>
      <webElementGuid>9c6b366c-4d21-4633-a5cc-fbb2e659ffe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[7]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>1cc273bc-7a2b-4bd9-99e1-28593f4034f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mdb-accordion-head-568' and (text() = 'How does the Trip Interruption benefit work?' or . = 'How does the Trip Interruption benefit work?')]</value>
      <webElementGuid>29095304-1192-4b65-85d0-d0570f98fc8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
