<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Can I transfer my plan if I sell my car_m_2c8249</name>
   <tag></tag>
   <elementGuidId>7fd19271-566c-46e7-8528-ed19ff71f841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faq-button-5 > i.mdb-accordion-indicator.rotate-icon.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-5']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1e711d11-2d82-43cd-8fb9-5733e53a9c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cde33caa-f4bf-4b37-8544-a234b79e75a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdb-accordion-indicator rotate-icon ng-star-inserted</value>
      <webElementGuid>130566f7-e4fa-4309-a822-a52ba7d0f548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-5&quot;)/i[@class=&quot;mdb-accordion-indicator rotate-icon ng-star-inserted&quot;]</value>
      <webElementGuid>21829b77-7f9a-4562-b1ae-3fe93f287eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-5']/i</value>
      <webElementGuid>aa5b00a5-1ec0-4a7d-a812-5d18337a7dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[4]/div/mdb-accordion-item-head/div/a/i</value>
      <webElementGuid>f9d047ae-0165-41e5-8b0e-c98b9cd82313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
