<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify Email Address_verifyEmailAddress</name>
   <tag></tag>
   <elementGuidId>dc3bb5fe-29dd-4f21-9803-26e1e0288b1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verifyEmailAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verifyEmailAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a14f08c-26bd-4b58-a34b-ede71dc8f053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>b0ad1a2d-87f2-486e-b108-71c2185bd78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5bec0ce7-81c2-4a3f-a77d-8b0c6a29d55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verifyEmailAddress</value>
      <webElementGuid>878a6d6e-d15d-4b88-88e8-1b2e55248c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verifyEmailAddress</value>
      <webElementGuid>3a2fb055-7c54-4be5-a59c-57fa3c210925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifyEmailAddress&quot;)</value>
      <webElementGuid>000eb84b-3952-4878-ad99-a67efbc4e9b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verifyEmailAddress']</value>
      <webElementGuid>177f05ba-53f1-4ea3-90d3-3caac40712b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div[6]/div/div/input</value>
      <webElementGuid>bbdd8376-38f5-48d4-b234-df38d587a8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>55cb3a92-c1d6-4ff8-ab58-4f63dceef0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'verifyEmailAddress' and @id = 'verifyEmailAddress']</value>
      <webElementGuid>34b7ac66-258c-4fe3-9fc5-d5f2fd164e43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
