<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_lever1_vroom</name>
   <tag></tag>
   <elementGuidId>0e0dd888-1403-4798-b72e-59f550dae8d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>(//span)[25]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainContent&quot;]/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div[1]/section/form/app-add-ons/section/div[2]/div/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
