<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Agreement and Exclusions</name>
   <tag></tag>
   <elementGuidId>8eba70c9-6b39-4fed-b285-4f5806ee4fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-view-sample-contract-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cart-view-sample-contract-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2a636e3-b818-4422-b141-d797deab5cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>9a968e1f-056d-4fa1-ba3e-1e0c792cc6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af52af17-7aa4-4be7-a2b9-193d7e3bb92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-view-sample-contract-btn</value>
      <webElementGuid>4671ea9e-81a2-4092-8bc8-ed1543ccb2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-text</value>
      <webElementGuid>d1dec4bc-d3a3-4c47-821e-9c1d194b4cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Agreement and Exclusions</value>
      <webElementGuid>07fd6198-82d0-4781-a67d-97b70e2e8587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-view-sample-contract-btn&quot;)</value>
      <webElementGuid>0250278e-bae1-42ac-92f1-2cf69e9c316e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-view-sample-contract-btn']</value>
      <webElementGuid>0cb499d9-a57c-4d4f-906b-f1b18f654f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div/app-cart-items/div[2]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>dee36611-df6e-4005-bcd6-f6a05b3a2185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Agreement and Exclusions')]</value>
      <webElementGuid>dea7e520-e8e9-4871-9c40-66bc0d9c0f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::a[1]</value>
      <webElementGuid>fa911efd-c180-4930-a8f3-843da011d589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lift Kit/Tire Modification Coverage: No'])[1]/following::a[2]</value>
      <webElementGuid>0ccf0502-f37e-4f1d-b801-95dc3c6235b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Options'])[1]/preceding::a[1]</value>
      <webElementGuid>90e965df-9dfd-40c9-9f44-6c03177f8c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreement Date'])[1]/preceding::a[1]</value>
      <webElementGuid>d543a7ae-579d-4a12-992e-3df8f6d8d617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Agreement and Exclusions']/parent::*</value>
      <webElementGuid>f7f06125-b261-4dde-82fe-4dde265db5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>9b3338b3-1aa4-4394-bf6d-d448dc827f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cart-view-sample-contract-btn' and (text() = 'View Agreement and Exclusions' or . = 'View Agreement and Exclusions')]</value>
      <webElementGuid>c88503ac-8811-4a66-b3e4-73b7463522a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
