<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View Payment Options</name>
   <tag></tag>
   <elementGuidId>40573bb1-3c75-4c86-b480-9fcb9debc94d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-to-cart-button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-cart-button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fcad27d-bf08-4b6c-83ac-e7875e5edb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> View Payment Options </value>
      <webElementGuid>c8e41473-1b6f-47c1-9f0a-864f408ba0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-button&quot;)/span[1]</value>
      <webElementGuid>1b0fdf05-bf63-4e5d-80de-c114675902ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='add-to-cart-button']/span</value>
      <webElementGuid>28004a0f-bf67-4270-bad3-a3a3b2dcfd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::span[1]</value>
      <webElementGuid>b4fc6d33-af3e-434d-90aa-09e8011debbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum Coverage Overview'])[1]/preceding::span[1]</value>
      <webElementGuid>920540b8-315c-427c-b2e3-fd62dc92a519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Customer Agreement &amp; Exclusions'])[1]/preceding::span[1]</value>
      <webElementGuid>e36ae18c-6ba9-4f8c-8e13-6232ea21c2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button/span</value>
      <webElementGuid>84ef300b-8211-4a3b-bbb8-343db10ea232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' View Payment Options ' or . = ' View Payment Options ')]</value>
      <webElementGuid>7375b9e8-d96f-4027-8add-c2986e674ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
