<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_COMPLETE</name>
   <tag></tag>
   <elementGuidId>37b0af94-1197-4d73-87ac-7423f7e47612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='address-verification-complete-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-verification-complete-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf4cd173-4e85-44c9-956e-9d709a54d266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-verification-complete-btn</value>
      <webElementGuid>e35ad25f-422e-4da4-9f18-558683c06922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>44b764d9-ee65-40b9-ad8f-9162f643c7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn waves-light</value>
      <webElementGuid>58595001-ec6b-42b7-b7fe-6d577fadae49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMPLETE</value>
      <webElementGuid>1dea092f-dda3-4ca6-b2e0-9ac65bfcda52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-verification-complete-btn&quot;)</value>
      <webElementGuid>63f384fe-63a8-43ed-8a11-81368b7475ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='address-verification-complete-btn']</value>
      <webElementGuid>08845c07-3914-419d-8ee7-eafe8ff955ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::button[1]</value>
      <webElementGuid>52913e9e-1e81-47a4-ab61-159d272c192b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Verification'])[1]/following::button[1]</value>
      <webElementGuid>9cd261ee-b580-4769-ab0d-e2eae782c203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COMPLETE']/parent::*</value>
      <webElementGuid>2109b5cf-2ffa-4ae9-80bf-6fe4b5386d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>3723526a-7b92-43a5-abd5-8de9ca31b98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'address-verification-complete-btn' and @type = 'submit' and (text() = 'COMPLETE' or . = 'COMPLETE')]</value>
      <webElementGuid>0e00e242-bd11-40cc-b83f-e3d40973c0b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
