<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Your Email_emailFormConfirm</name>
   <tag></tag>
   <elementGuidId>0327cd2d-b15e-4269-9e1e-2c39a3fffa4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailFormConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff989f55-60e7-433a-91a0-e28d8a96872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e7e5fa62-a698-4dda-9e8a-8d0c2303aa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormConfirm</value>
      <webElementGuid>15b4818f-30ad-485b-9c3b-3018ad1bda4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>35d879f7-3fff-4271-92e2-1d13005148d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c170-16 validate-success validate-error ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>403e6d8f-7649-41d1-b790-382276f4cc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormConfirm&quot;)</value>
      <webElementGuid>9cae8c6a-f1a8-4c6d-ac5c-9ecdd27252d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormConfirm']</value>
      <webElementGuid>338e606c-36f7-4fb5-81b6-fd7fff5b2cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[3]/div/div/input</value>
      <webElementGuid>0a059eef-9162-45d9-997c-33288d533639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>15b6ef74-56f6-40bc-a945-473a7dea7629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailFormConfirm']</value>
      <webElementGuid>61e9a682-0b5d-4e4f-875e-54335cddd6b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
