<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_January February March April May Jun_0a059c</name>
   <tag></tag>
   <elementGuidId>c66a592a-6684-4bef-9f8a-237d97d9cbdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expoDateMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expoDateMonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed400e97-f692-4258-a38a-a16da6e7f277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3879b9f8-9307-4b3b-91ea-f2184e75d564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expoDateMonth</value>
      <webElementGuid>0479f575-c95c-420a-8dc9-e600e3aa52b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exp Month *</value>
      <webElementGuid>c9782306-fbe6-477e-8b10-febc6c981f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expirationMonth</value>
      <webElementGuid>43d53121-b99f-438e-be51-0373411a3c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6e586ee1-497e-4ccd-994a-a538689bc276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  January February March April May June July August September October November December</value>
      <webElementGuid>78ac3ad8-f2d9-44b6-8f95-b7a4308057d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expoDateMonth&quot;)</value>
      <webElementGuid>d19a9be0-9eee-4170-9a16-2f2057eae596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expoDateMonth']</value>
      <webElementGuid>14feb4da-1ccc-4c05-8332-d7d64af61b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[3]/div/div/select</value>
      <webElementGuid>cd39e714-05eb-4a71-803d-3bd902e8ed08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Month'])[1]/following::select[1]</value>
      <webElementGuid>6550331e-9a39-46dc-9a66-1256752991ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/following::select[1]</value>
      <webElementGuid>0ba7cd04-2d63-4f05-b710-cd9a6270a90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Year'])[1]/preceding::select[1]</value>
      <webElementGuid>f88b8c85-a388-427a-9da4-f6c3f8c99df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVC'])[1]/preceding::select[2]</value>
      <webElementGuid>99d4ff29-32bb-4bc8-b50e-3eec3ebae5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c5ec3464-0230-466e-ba6e-a806919d46fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expoDateMonth' and @placeholder = 'Exp Month *' and (text() = '  January February March April May June July August September October November December' or . = '  January February March April May June July August September October November December')]</value>
      <webElementGuid>3e664dfb-b157-4bdb-84c9-bded629e1b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
