<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name on Card_billingFormName</name>
   <tag></tag>
   <elementGuidId>de7c1bdc-40fe-4ede-be36-94ee3114ae85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingFormName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billingFormName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6914232d-174f-4611-99c8-0810604029ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8478837c-6b3c-4aa0-a538-4af3cf6c8774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFormName</value>
      <webElementGuid>d45ffd9d-10ec-4cad-9912-1887d1402f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cardName</value>
      <webElementGuid>62c873e3-4b7c-418d-af96-31f3955baca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>916b55ff-6c47-44bc-8d2f-af829f74cc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFormName&quot;)</value>
      <webElementGuid>eba64d7b-35be-4407-9481-6d806ae2033d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingFormName']</value>
      <webElementGuid>e8c4d4ed-1608-4516-b4c7-efa11b7a71a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div/div[2]/div/input</value>
      <webElementGuid>c427258f-1c67-44f7-8b3a-35d3b46b7104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c171cb2d-3300-459e-88ae-a59b0b353bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingFormName']</value>
      <webElementGuid>fb5105d1-79aa-4ed5-8b00-267bc2b824c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
