<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How does the Trip Interruption benefit work</name>
   <tag></tag>
   <elementGuidId>086d6895-2159-4d75-9c05-e8c04ed5af85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mdb-accordion-head-568']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mdb-accordion-head-568</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98006eb8-6b94-4ddd-8c1c-db72ac837a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>df656bc5-f352-47ee-a9a1-d1d407e4598a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdb-accordion-head-568</value>
      <webElementGuid>f1023992-738c-476e-8f9e-092f958f6cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How does the Trip Interruption benefit work?</value>
      <webElementGuid>7f293672-549f-44ff-8dba-7276368b59ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdb-accordion-head-568&quot;)</value>
      <webElementGuid>8b4871c4-8424-4d77-8fbf-0b45be6571db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mdb-accordion-head-568']</value>
      <webElementGuid>9703d7b5-5749-4434-9464-9f830f6d5dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[3]/div/app-slice-faq/div/div[2]/div/div/div/div/mdb-accordion/div/mdb-accordion-item[7]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>2c91065e-e310-409e-91c6-7c134468b08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Agreement'])[3]/preceding::div[2]</value>
      <webElementGuid>256fcd07-dd4d-4983-8749-a7f3781e6d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[7]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>63d91992-537a-4800-8958-3b1e3ce092a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mdb-accordion-head-568' and (text() = 'How does the Trip Interruption benefit work?' or . = 'How does the Trip Interruption benefit work?')]</value>
      <webElementGuid>95e2069f-8a4c-4a9c-a954-c6417cdaf8ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
