<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Can I cancel my plan_mdb-accordion-indica_027e87</name>
   <tag></tag>
   <elementGuidId>37e6f294-fd7b-440d-9c69-bd971784d0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-3']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#faq-button-3 > i.mdb-accordion-indicator.rotate-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>74a7b8c4-93cf-4dab-94e7-06f5a7fb91d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56c5f5fa-5d2d-4e64-bd59-64d1430c9334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdb-accordion-indicator rotate-icon ng-star-inserted</value>
      <webElementGuid>bd750530-ec01-4ac6-bcc3-23093a2ee5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-3&quot;)/i[@class=&quot;mdb-accordion-indicator rotate-icon ng-star-inserted&quot;]</value>
      <webElementGuid>004a6309-4ccf-4c04-a3eb-8c7339b78952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-3']/i</value>
      <webElementGuid>d499acd3-259a-4b83-bcce-8a8eb67943bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[3]/div/mdb-accordion-item-head/div/a/i</value>
      <webElementGuid>7acebb06-2b20-479d-a4ac-b5be356a25d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
