<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms and Conditions</name>
   <tag></tag>
   <elementGuidId>6efc5424-64ed-4497-b4fb-0a1aa7becd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4 > a.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fba06ce4-46d9-401a-adb4-740591fe5eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c606b314-be96-428b-b1d6-665637f49266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>6b065dfa-89e0-4994-9cbe-e197567b0312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>023aaf71-b7ec-452d-8fca-04f370999e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Terms and Conditions (opens in a new tab)</value>
      <webElementGuid>39d11ac4-1fc9-4d05-b6b6-4ce89a67c9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/legal/terms-and-conditions</value>
      <webElementGuid>f7a85e8a-f5b2-45a2-a868-0388a55ceed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/legal/terms-and-conditions</value>
      <webElementGuid>c7c9fcbb-6d2a-444b-ab9d-6ef70a72533f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>0f9bdd09-7c09-4a38-9167-0a2164f21445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms and Conditions</value>
      <webElementGuid>902b8766-7885-43f6-9d81-a637d58e1c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c157-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-footer[@class=&quot;ng-tns-c157-0&quot;]/app-footer-contact-us[@class=&quot;ng-star-inserted&quot;]/footer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;footer-copyright text-center p-4&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-8 row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>25a0dd1f-6a62-4b39-8c13-329bf9c1ebcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      <webElementGuid>f69a28f8-901c-43e0-ba76-c775a3a0eb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms and Conditions')]</value>
      <webElementGuid>e2f44529-44ba-4d4f-8f27-1c1fef5e91c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sales@oneprotectplans.com'])[1]/following::a[1]</value>
      <webElementGuid>f0c82096-822c-4c56-9a38-a7d4eccf97cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(833) 954-0085'])[3]/following::a[1]</value>
      <webElementGuid>ceb33a39-2025-45af-9b21-151c3c33643a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::a[1]</value>
      <webElementGuid>42189518-ab5c-43a9-a191-e650dc69943f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::a[2]</value>
      <webElementGuid>3cb30635-5a89-4cd3-a7f4-3bda8cf49e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terms and Conditions']/parent::*</value>
      <webElementGuid>18b52090-df8c-4788-a23a-08641ae785e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/legal/terms-and-conditions')]</value>
      <webElementGuid>f1e3bd38-3da8-4ffb-9b51-4de144a60b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>e21de730-2373-4200-91cc-eeb8f618b215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/legal/terms-and-conditions' and (text() = 'Terms and Conditions' or . = 'Terms and Conditions')]</value>
      <webElementGuid>c2f4e8d6-41a5-480b-ab5c-9a2b0e11e610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
