<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW AGREEMENT  EXCLUSIONS</name>
   <tag></tag>
   <elementGuidId>743aadef-ac90-4bd5-87fc-6287b28652d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-view-sample-contract-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-view-sample-contract-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3df5889f-ece6-40b8-a03c-9d1bc8200eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>b25bc12b-1ec8-4181-b79a-8b62c110369a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0cdeefde-ee57-4532-91f2-a6d5308c332d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-view-sample-contract-btn</value>
      <webElementGuid>85c918a4-616c-4747-9b5f-94b0b4f298a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-text</value>
      <webElementGuid>6f959805-5935-4703-980e-c76c60fa33ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW AGREEMENT &amp; EXCLUSIONS</value>
      <webElementGuid>f86f6424-211d-4bfb-80eb-4921629ec5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-view-sample-contract-btn&quot;)</value>
      <webElementGuid>48813206-3923-47dc-8e4e-8d342b8a3225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-view-sample-contract-btn']</value>
      <webElementGuid>51926ffa-86d9-4e08-952c-868a83560d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div/app-cart-items/div[2]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>c4a8369b-2fb2-4906-bef4-83c89728adfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>b8d6a39f-1db8-4f26-b76b-f4b517755741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMOVE'])[1]/following::a[1]</value>
      <webElementGuid>9a84e5fa-5e39-41a4-acbf-419d26bdc638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::a[2]</value>
      <webElementGuid>0423cf80-7409-4c78-9a3b-c9b3f729d468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='payment options'])[1]/preceding::a[1]</value>
      <webElementGuid>e01325c5-5e5d-4e05-8b61-bf503eba758d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Starts'])[1]/preceding::a[1]</value>
      <webElementGuid>f806ec55-2c18-4e71-9c97-3837b82a6e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VIEW AGREEMENT &amp; EXCLUSIONS']/parent::*</value>
      <webElementGuid>e57eb6d4-f902-46fa-8616-488dc0678c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>0a987c1a-1fb6-4c1c-b7e4-4039f7ada498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cart-view-sample-contract-btn' and (text() = 'VIEW AGREEMENT &amp; EXCLUSIONS' or . = 'VIEW AGREEMENT &amp; EXCLUSIONS')]</value>
      <webElementGuid>193b9940-a280-4246-a635-7b2e90d9f567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
