<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT</name>
   <tag></tag>
   <elementGuidId>ea1f17c2-33b4-48e6-968f-9775e1c0fc07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-checkout-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cart-checkout-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7b6c5e5f-9c95-445f-840f-cd9b37e9db83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-checkout-btn</value>
      <webElementGuid>5219270a-a218-48c8-a0e4-ab2c32c01709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn w-100</value>
      <webElementGuid>3fe1a4b5-f094-4632-8e54-e60e4303dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT</value>
      <webElementGuid>86eccd28-1dd4-485e-a105-50ac5786b4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-checkout-btn&quot;)</value>
      <webElementGuid>544d73e7-33c5-4356-a259-babe7447ca44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cart-checkout-btn']</value>
      <webElementGuid>2be4a270-7928-490d-91ef-8adc3d2276fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-shopping-cart/div/div[2]/mdb-card/mdb-card-body/mdb-card-text/p/div/div[2]/app-cart-payment/div/mdb-card/mdb-card-body/div[3]/div/button</value>
      <webElementGuid>f1a8c7bb-92ec-4fc9-9907-be370ac0189c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Tax is estimated. Total tax amount is applied in checkout.'])[1]/following::button[1]</value>
      <webElementGuid>c85ab1ae-b943-4ff5-a3fc-eb5f487da765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$299.02'])[1]/following::button[1]</value>
      <webElementGuid>b838ce8b-57a7-44d1-b1b1-e4da840846e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schomp Ford'])[2]/preceding::button[1]</value>
      <webElementGuid>1db0c16c-5e25-494d-a3a0-d7bd4bb20c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::button[1]</value>
      <webElementGuid>63cc4bf4-796f-4391-89c6-c50ca5b41987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CHECKOUT']/parent::*</value>
      <webElementGuid>e44b74da-a111-44bc-b74c-76a38713448f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>e60aca23-5c1b-410a-9270-9a3bc177c28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cart-checkout-btn' and (text() = 'CHECKOUT' or . = 'CHECKOUT')]</value>
      <webElementGuid>3e3fc321-4809-4baf-b066-cb337327825c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
