<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Your Price</name>
   <tag></tag>
   <elementGuidId>89fee2e4-3951-4400-bb88-b333d340fdfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-component-see-pricing-btn-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modal-component-see-pricing-btn-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca8111ef-4276-4d4b-bf7f-cff87939d242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6340bbec-0b68-4e83-b20e-a1361d42f102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-component-see-pricing-btn btn primary-btn flat waves-light</value>
      <webElementGuid>bdccf7c1-a389-4667-b65e-098eefd62b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-component-see-pricing-btn-0</value>
      <webElementGuid>11030dc4-6288-4ebb-a984-76189450f738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Your Price </value>
      <webElementGuid>98c64c56-3c52-4141-9018-5fdb094cbd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-component-see-pricing-btn-0&quot;)</value>
      <webElementGuid>a4d0ff58-44e7-4310-82c0-0402f3a83531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modal-component-see-pricing-btn-0']</value>
      <webElementGuid>3b78c2dd-af04-4de1-be89-3ebbf4ca0a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div[2]/div/div[3]/form/div[3]/div/button</value>
      <webElementGuid>5a503cdc-d5f8-446c-813f-e7a6468bb1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your odometer.'])[1]/following::button[1]</value>
      <webElementGuid>5067ede3-f027-40eb-a1bc-38c0d7be4e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current mileage'])[1]/following::button[1]</value>
      <webElementGuid>8e6c792a-ce1b-4cde-b65f-de1064a83c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>2a1ca695-c4ad-4e2a-92c1-d442abe46253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'modal-component-see-pricing-btn-0' and (text() = 'Get Your Price ' or . = 'Get Your Price ')]</value>
      <webElementGuid>f139f376-5fe6-42f6-93de-0c765961b51b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
