<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CardType</name>
   <tag></tag>
   <elementGuidId>8ba27e16-307c-4445-8c82-b4d1bede6216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_type_001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card_type_001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6aaddac-21e8-4de1-8489-358f4578b163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0eb7c919-c719-4c87-bda5-a5f9ec219274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_type</value>
      <webElementGuid>e104f96b-be93-40e4-a665-23971e6bc690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_type_001</value>
      <webElementGuid>28eb6676-3f6e-471d-bda5-750a3f94e5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>001</value>
      <webElementGuid>5f8a02f0-38de-471b-8165-60b400b6994f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_type_001&quot;)</value>
      <webElementGuid>000a992d-0358-4776-bac2-57b6695ab7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VSC/VolksW/iframe_payment-processor</value>
      <webElementGuid>727b9fde-24a5-4ddf-b3b7-16285333a16a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_type_001']</value>
      <webElementGuid>ddea82b7-7d61-4367-805e-e943d4dc47ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card_type_selection']/div/input</value>
      <webElementGuid>dcaa7e90-707f-4d95-85dc-d222621168ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/fieldset/div/div/input</value>
      <webElementGuid>174dcd7c-5d1d-4f12-9d77-b8d736c1664d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'card_type' and @id = 'card_type_001']</value>
      <webElementGuid>fc3c3889-fdd1-4fd1-b30b-9abb6ea944d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
