<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_coveredMiles</name>
   <tag></tag>
   <elementGuidId>0c28a70d-8c17-4cef-b6f3-74ed991f81fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedTermMileage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedTermMileage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>447c86b9-1b67-418e-afc7-62d09c30e465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>43777b89-3f4e-448e-98d9-325834c83c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedTermMileage</value>
      <webElementGuid>da9e4df9-98b6-425f-b4bc-e030133db2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedTermMileage</value>
      <webElementGuid>0187216c-76f0-4391-ac03-a4b38222cae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select60,00072,00085,000100,000120,000</value>
      <webElementGuid>a7ef51a2-7458-41a6-84f8-ea0300e2288d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedTermMileage&quot;)</value>
      <webElementGuid>9cba300b-27db-48d7-a839-be63d3d46651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectedTermMileage']</value>
      <webElementGuid>4c58499c-e5e5-4eaa-98ff-a76ce6e846f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>a52a8b43-8fc0-4cb6-8e1b-a57afd105d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250'])[1]/following::select[2]</value>
      <webElementGuid>15c9dc6c-2c47-4af2-98fb-480bb284c43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[1]/following::select[2]</value>
      <webElementGuid>5506a104-0963-42ed-99bf-cd797f1cdd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time'])[1]/preceding::select[1]</value>
      <webElementGuid>cdf53a88-30a4-4472-b407-fef9f3f3e01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installments'])[1]/preceding::select[1]</value>
      <webElementGuid>e206230c-e1e0-4216-8363-a0843cae7a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>2af8c2df-7162-4fd2-8433-2d3074156269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'selectedTermMileage' and @id = 'selectedTermMileage' and (text() = 'Please select60,00072,00085,000100,000120,000' or . = 'Please select60,00072,00085,000100,000120,000')]</value>
      <webElementGuid>7bbcec15-db83-4c86-b470-12895d80104d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
