<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current mileage_editVehicleOdometerVIN</name>
   <tag></tag>
   <elementGuidId>e8fa6a8b-4968-40d2-833c-7966ed32d131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editVehicleOdometerVIN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editVehicleOdometerVIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36e34056-375c-4c47-bcb2-233958fcd03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>odometerlabel</value>
      <webElementGuid>b4fca4a5-7556-448a-a8a7-a1f63f7b82a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8125d9ab-7df1-40a2-a7a2-b829f42c11e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>d783d323-f426-4eff-ae7f-1ed15637bbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>9d32486a-d46b-4517-a9f9-bbf7d6478b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>165b3882-d67f-4c9c-b86d-40ddf179daa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editVehicleOdometerVIN&quot;)</value>
      <webElementGuid>e04f7ba7-8d8f-4ade-9d78-4a3761c68223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0199dc32-d051-4488-9028-ccb3369277aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>odometerlabel</value>
      <webElementGuid>1fa8f417-221d-4a5f-a577-d6b698450841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc71f4ba-ba9e-440b-b2e6-48000d2719da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>d671b7de-5b41-4897-a278-fb286c85393c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>editVehicleOdometerVIN</value>
      <webElementGuid>e49ee806-ee7b-47e7-80c6-004179de47c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>664db931-f9af-462a-be5f-85fe3afab396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editVehicleOdometerVIN&quot;)</value>
      <webElementGuid>8ee566f1-18ce-4e78-832c-384af5227595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editVehicleOdometerVIN']</value>
      <webElementGuid>100b7bdd-10a6-4aa1-b25a-44dc30de2de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div[4]/div/div/app-component-vehicle/div/app-verify-vehicle/div/div/div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>a2ab6305-3daa-4d94-b644-fef6d424a98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>142a39f6-c554-433f-884f-4ba353e51350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'editVehicleOdometerVIN']</value>
      <webElementGuid>3bc898be-0214-4735-b69b-b2af470a00ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
