<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADD COVERAGE</name>
   <tag></tag>
   <elementGuidId>e48f4416-e8f9-437c-a8a6-fc2d7a1832ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cta-button-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cta-button-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d72a860-a406-4869-b504-f623da55c649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbf63617-8143-43bf-84c1-7d1c039d4c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20740e58-f8a2-4cbe-b97e-6c2977284c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn cta-button mb-4 primary-btn</value>
      <webElementGuid>e353c1b6-9258-4030-9453-8a724443f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cta-button-1</value>
      <webElementGuid>7b4aca90-268f-4b89-83ba-6532560b8678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD COVERAGE</value>
      <webElementGuid>1502c9ad-620b-4238-a23b-9d3434e8e876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta-button-1&quot;)</value>
      <webElementGuid>e07d8fc9-722b-42b0-bbd9-21279628aebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cta-button-1']</value>
      <webElementGuid>675f387e-94d4-4d67-afbb-49e28a4e5c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[7]/div/app-slice-content-block/div/section/div/div/div/div/app-component-cta/div/a</value>
      <webElementGuid>bc13e0b6-e7e1-45fa-a460-333f777265d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD COVERAGE')]</value>
      <webElementGuid>9fb86fbd-1cb5-4a62-b2a7-39656823ebf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Agreement &amp; Exclusions'])[2]/preceding::a[1]</value>
      <webElementGuid>133f7feb-feeb-4b5f-88b5-241c911d3fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD COVERAGE']/parent::*</value>
      <webElementGuid>c294cb14-6214-4be2-a423-c702438ea6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/app-slice-content-block/div/section/div/div/div/div/app-component-cta/div/a</value>
      <webElementGuid>e8e8d254-bb2d-4db0-b7e2-e0608b76750a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cta-button-1' and (text() = 'ADD COVERAGE' or . = 'ADD COVERAGE')]</value>
      <webElementGuid>5c08b6e1-3833-4d73-922d-72235f98b987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
