<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_English - CA Franais - CA</name>
   <tag></tag>
   <elementGuidId>b430b430-75b7-45b6-90e5-13c85344590b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.ng-tns-c162-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='languageDropdown']/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d6deda9b-6e48-4245-a0d2-6c3b07ae19cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c162-0</value>
      <webElementGuid>e01013ea-adc2-4633-8c9c-df90736543c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> English - CA Français - CA</value>
      <webElementGuid>78610075-e4d5-4078-b61d-71623b81fc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languageDropdown&quot;)/select[@class=&quot;ng-tns-c162-0&quot;]</value>
      <webElementGuid>391c3c59-9cbd-473d-a30d-62fd39f6ba0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='languageDropdown']/select</value>
      <webElementGuid>8d4c49cb-0828-43ac-ae13-ce2887825b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v 6.2.0'])[1]/following::select[1]</value>
      <webElementGuid>ea5451fd-ec28-4384-9803-f9ae7b864571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/following::select[1]</value>
      <webElementGuid>a7ae8994-5da8-427e-8bb5-e84d79422df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::select[1]</value>
      <webElementGuid>c3312b77-c5d9-4936-92d2-b2f894679c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::select[1]</value>
      <webElementGuid>c6ea4d8c-a6c4-458a-9410-bf9c8968f951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-root/div/select</value>
      <webElementGuid>0ae939eb-59c5-4d75-9aca-9361369d006e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' English - CA Français - CA' or . = ' English - CA Français - CA')]</value>
      <webElementGuid>5d8bebeb-9a36-442f-a7aa-75ccd022dcb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
