<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADD COVERAGE</name>
   <tag></tag>
   <elementGuidId>242185c4-605f-43e1-852a-6f929c85a27b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cta-button-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cta-button-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5653306-5818-4dcb-a111-5e8edef2059c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95108054-3fb3-4858-8e4e-a54e03ac691a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54ac218a-3be2-4074-886b-9f07905f2075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn cta-button mb-4 primary-btn</value>
      <webElementGuid>05e53910-93db-4133-91e5-5ddc64eadd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cta-button-1</value>
      <webElementGuid>289da637-ef98-4607-baa0-1ff9d4e01191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD COVERAGE</value>
      <webElementGuid>ec331174-ccfb-49d4-b966-e77f7e4596ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cta-button-1&quot;)</value>
      <webElementGuid>89a91da0-ee5f-4a15-a985-bbd26b2633ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cta-button-1']</value>
      <webElementGuid>28d0f2d0-5bac-4d81-b88c-7fde237df921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[7]/div/app-slice-content-block/div/section/div/div/div/div/app-component-cta/div/a</value>
      <webElementGuid>e9feab4b-609c-4b12-8561-edd88beeab2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD COVERAGE')]</value>
      <webElementGuid>3157cd4c-e709-4ab4-bb66-e30d2ff93373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Agreement &amp; Exclusions'])[2]/preceding::a[1]</value>
      <webElementGuid>9562b316-5b7a-46cc-84cb-c4964f7b7d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD COVERAGE']/parent::*</value>
      <webElementGuid>a7a40089-c37d-42c9-b833-dcb89ea798b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/app-slice-content-block/div/section/div/div/div/div/app-component-cta/div/a</value>
      <webElementGuid>bccf6023-6882-4cfa-b718-b6c39d3a4f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cta-button-1' and (text() = 'ADD COVERAGE' or . = 'ADD COVERAGE')]</value>
      <webElementGuid>d0c0e9c1-fe8a-4fdf-9ce4-46ec7db0cdc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
