<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary Phone Number_secondaryPhoneNumber</name>
   <tag></tag>
   <elementGuidId>5b8b800e-da0d-4ec4-ba8f-cf352df5cb48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondaryPhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondaryPhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf8d216b-b1ab-4af6-bf6f-2037a9b06c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>08ab6f08-5d44-43d4-a4aa-0843bd15bf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c2a49e23-52f8-4b74-8d5d-2260d955ae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondaryPhoneNumber</value>
      <webElementGuid>b844639c-7800-4043-9709-68a8470239a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondaryPhoneNumber</value>
      <webElementGuid>85a3ad18-c71e-41bb-a3f0-08a7e27564d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9b2334bc-b965-44bf-8bb2-f799db18e553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondaryPhoneNumber&quot;)</value>
      <webElementGuid>b3bc90f1-090c-421a-80ad-a05d467a585c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondaryPhoneNumber']</value>
      <webElementGuid>b72e342e-5224-446e-ac8a-9e3afa03b28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div[4]/div/div/input</value>
      <webElementGuid>3db6355c-b4d0-404b-a98e-efe19bac6d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>9c5632bc-9bb7-4234-8c41-f4a864b19720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'secondaryPhoneNumber' and @id = 'secondaryPhoneNumber']</value>
      <webElementGuid>50010c2f-1117-47b0-a1f3-50e2d59577e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
