<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_customerZipCode</name>
   <tag></tag>
   <elementGuidId>ca417c9a-3851-471b-9b8f-faa37d3bc73e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerZipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerZipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce01c4ce-b718-4412-9948-6b733900fb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>b3704488-c7df-42e2-810a-8a72716aa6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c6c86f2-02c9-4460-921d-cbe91b7c6677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerZipCode</value>
      <webElementGuid>606b1fa0-29a9-4f0c-bfdc-51bf3bc123f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerZipCode</value>
      <webElementGuid>09a1285c-8688-42b1-b5d4-eda8be4d6bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerZipCode&quot;)</value>
      <webElementGuid>8919b9bb-decc-47a1-9e3e-65f558a6489e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerZipCode']</value>
      <webElementGuid>40df6631-0801-4bab-ac67-378681cb802c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div[11]/div/div/input</value>
      <webElementGuid>5ae0a190-4b55-48ac-826d-d022490403a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>23b1ccbd-a5bc-4f06-a8af-565b3df2fcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerZipCode' and @id = 'customerZipCode']</value>
      <webElementGuid>d31e0410-399f-4021-8238-38211ba9787f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
