<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIN_vin</name>
   <tag></tag>
   <elementGuidId>125f2206-a851-4bd0-81ea-4f3a699c253d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebb51a39-5389-49bb-95c3-278be56d9dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>b15f804e-66da-4cd6-a1ac-37bde9d0972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebec4236-81d2-41c0-9a5f-accfef450814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vin</value>
      <webElementGuid>7d1533b9-d84c-4586-b0da-7e62925472aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vin</value>
      <webElementGuid>1ed5437a-aa2c-4437-91ec-dbd915d918e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vin&quot;)</value>
      <webElementGuid>33c0afcf-af37-4543-b005-c219dc1232c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vin']</value>
      <webElementGuid>32ab1f04-4a59-400a-a820-b0f34a9f7cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/section/div/div/div/div/form/div/div/div/input</value>
      <webElementGuid>80885fbb-79b8-49b7-ac85-ffcd1203ab54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4243d525-02a9-47ba-8193-eb16343fb1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vin' and @id = 'vin']</value>
      <webElementGuid>37389573-1418-4030-b281-45e10e32accf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
