<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_customerFirstName</name>
   <tag></tag>
   <elementGuidId>9189dc80-6d2f-4e57-a8ae-f6ea21279654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad01dfc7-23c9-4f6a-8f8e-e2acc65cdf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>dcab4dcb-3e16-4844-8f55-eaba0312f9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c409be9d-e7c5-4ac7-ba95-880e78f07ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerFirstName</value>
      <webElementGuid>09af1f64-1820-4109-a809-272784c0d89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerFirstName</value>
      <webElementGuid>c6177bc4-fcdf-44bf-95b9-fdd1c39d31d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerFirstName&quot;)</value>
      <webElementGuid>34545dcb-c71b-4ec6-b262-50573b9f22ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerFirstName']</value>
      <webElementGuid>218d74c5-2151-4593-bc81-4211ef291796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div/div/div/div/div/input</value>
      <webElementGuid>ce1dcce5-a28b-4fa4-bbc9-ba2fc2b24d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>80299d91-dab2-49b2-b4e2-3e2a52e003ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerFirstName' and @id = 'customerFirstName']</value>
      <webElementGuid>990cd923-f882-4903-ab25-3ca73f004ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
