<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current Odometer Reading_odometer</name>
   <tag></tag>
   <elementGuidId>1aee7b97-6d58-4c07-b58f-e60418c5934d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#odometer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='odometer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e36e665a-fd45-470c-b529-5c2d648f67b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>92828deb-f43e-4384-b2bf-508d9002ef96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83bc90f5-c7a6-4b6b-b5c8-a6c0ceaf1e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>odometer</value>
      <webElementGuid>19dd6e04-070b-44f4-b72c-0f0b80a06556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>odometer</value>
      <webElementGuid>0e769641-be74-43be-a766-beb57bbac6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;odometer&quot;)</value>
      <webElementGuid>f3decd92-f2ef-437d-8e31-674eb2c40e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='odometer']</value>
      <webElementGuid>c19d706e-dd0d-4bb4-9fb4-18024d594179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/section/div/div/div/div/form/div[3]/div/div/input</value>
      <webElementGuid>203c3cd8-7b94-4b67-9c5e-3b2fa17c3054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>58039187-3d23-424e-8cc6-5e6fcf61ccde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'odometer' and @id = 'odometer']</value>
      <webElementGuid>9b613b0a-9b66-49ac-93d8-ef0ac7365efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
