<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_customerLastName</name>
   <tag></tag>
   <elementGuidId>5d1b137f-06bb-4506-8bb1-4418da3b5371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d1e0cbf-6039-49dc-b20e-60e1b5babad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>a341a581-8f06-4612-a4d8-f2488a8eec99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd70ea43-8039-4be5-b998-87ef4f72e7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerLastName</value>
      <webElementGuid>bcef2ec8-5960-4c35-8521-263905ee97f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerLastName</value>
      <webElementGuid>23c0ce5d-0675-47a5-941f-4d03ce5cd35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerLastName&quot;)</value>
      <webElementGuid>fb6da632-56c2-4681-bad3-c3fed3cbdb34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerLastName']</value>
      <webElementGuid>127053f1-8656-4acd-b367-162b481ac24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div/div[2]/div/div/div/input</value>
      <webElementGuid>0c870ed2-2a1b-4f08-a89f-ed4adfb82473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>25242cf5-13a8-4375-9165-6d7e355bb058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerLastName' and @id = 'customerLastName']</value>
      <webElementGuid>85812db5-a71d-4156-9b01-72a53b101194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
