<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_customerAddress1</name>
   <tag></tag>
   <elementGuidId>fb74f459-5ffc-4c11-8f55-3110f3a1316b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerAddress1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerAddress1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>177bd4cb-01b8-4aa2-8ed9-2a34b0c0041d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>de2d29ba-537d-4531-9686-c5986765360c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>687d6ec5-b04d-47d0-b93c-eb50120c56c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerAddress1</value>
      <webElementGuid>fd8902b1-9ce2-4f36-827e-f787d9177ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerAddress1</value>
      <webElementGuid>2cd23868-135d-4370-8324-a17597115bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerAddress1&quot;)</value>
      <webElementGuid>e8443980-30f2-4595-bfbf-669c4c38bf15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerAddress1']</value>
      <webElementGuid>7c8555b8-f49b-499e-a2a0-cf2b4fdcfb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div[7]/div/div/input</value>
      <webElementGuid>23fb527d-79f4-4f91-9de1-e8666442ce7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>6fa68446-5b41-4313-9d60-f1a541fe128b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerAddress1' and @id = 'customerAddress1']</value>
      <webElementGuid>0b34e5f0-447d-4e06-9a17-8092d3dda81a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
