<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select4860728496120</name>
   <tag></tag>
   <elementGuidId>c123acb5-a74a-48ce-bafe-46c50d78c5e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedTerm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedTerm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>322157a7-77ab-44f2-9e41-55d4eef0bfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>f9046bc7-3a31-4def-b354-e20a870821f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedTerm</value>
      <webElementGuid>063a550c-0880-4fc4-b50c-e5b2f88ef789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedTerm</value>
      <webElementGuid>f292628f-841d-4009-a783-7a4e57e85254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select4860728496120</value>
      <webElementGuid>5b0407f6-4365-46f8-9c90-7c6db92493cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedTerm&quot;)</value>
      <webElementGuid>8ae5cd71-0fec-4a87-abd0-a97ac3a6c783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectedTerm']</value>
      <webElementGuid>b8920560-1ddb-4f3a-8c66-7cd2feb9bd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>c6b54873-dbe5-4c53-8c7a-b15de79ed20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250'])[1]/following::select[1]</value>
      <webElementGuid>3ba06858-24ca-47de-800e-baae9ab41ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[1]/following::select[1]</value>
      <webElementGuid>7136caec-9cc4-430f-a7b0-beb92ad04098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time'])[1]/preceding::select[2]</value>
      <webElementGuid>a9a177d8-0dc6-4b25-8b72-759450b51f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installments'])[1]/preceding::select[2]</value>
      <webElementGuid>c9ef84a4-33a5-4844-8e50-c01df51023c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>597dea76-641d-4f3d-af32-af347d2b4569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'selectedTerm' and @id = 'selectedTerm' and (text() = 'Please select4860728496120' or . = 'Please select4860728496120')]</value>
      <webElementGuid>f27d7880-e01f-4a45-a9ce-f08bbbbb7c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
