<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Platinum</name>
   <tag></tag>
   <elementGuidId>7ea10b8d-9329-431b-ad9c-ce0e808943cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.c-tile-select__body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/section/div/div/div/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>350d8b9a-1f52-477a-b8eb-4d138fafc001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-tile-select__body</value>
      <webElementGuid>775411c2-2d44-416c-bcd7-de143a4fd8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum</value>
      <webElementGuid>126a7fa3-83a9-466c-808c-344a17851968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/div[@class=&quot;u-pb&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;o-layout  o-layout--equal-height&quot;]/div[@class=&quot;o-layout__item u-1/3&quot;]/div[@class=&quot;c-tile-select&quot;]/label[@class=&quot;c-tile-select__label&quot;]/span[@class=&quot;c-tile-select__body&quot;]</value>
      <webElementGuid>05ae50aa-a8a5-45fd-919a-1f721e495f7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section/div/div/div/div/div/label/span</value>
      <webElementGuid>4febad93-e644-4033-8406-111b0cf7e18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your coverage level.'])[1]/following::span[1]</value>
      <webElementGuid>038a865e-de8a-4d9a-9ef5-875d675bf9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage level options.'])[1]/following::span[1]</value>
      <webElementGuid>62c8ca27-c1d7-402f-b29e-17d41dd5cdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gold'])[1]/preceding::span[3]</value>
      <webElementGuid>96664587-dea1-425b-99ed-5d7e59424d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>acd68a93-59d7-4dd6-9356-861f252c48ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Platinum' or . = 'Platinum')]</value>
      <webElementGuid>45507af8-7087-4579-9bf8-0d65fc73e907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
