<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Installments</name>
   <tag></tag>
   <elementGuidId>63aecd1b-ea88-4da2-8fd2-751dc1d189e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/section[2]/div/div/div/div/div[4]/div/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68eb77be-1b22-4f6a-b29d-3a9925fe2460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-button-group__label</value>
      <webElementGuid>8182074f-3b97-45b4-a5fe-7b53dddbe0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Installments</value>
      <webElementGuid>09eaea7e-cb64-4663-aa84-762ea3d4a011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/div[@class=&quot;u-pb&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item u-1/2 u-1/1@l&quot;]/div[@class=&quot;u-mt&quot;]/div[@class=&quot;c-button-group  c-button-group--auto&quot;]/label[@class=&quot;c-button-group__item&quot;]/span[@class=&quot;c-button-group__label&quot;]</value>
      <webElementGuid>68747d35-9d6f-4784-aa05-0089b73f5eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/div/div/div[4]/div/label[2]/span</value>
      <webElementGuid>ea2afeef-7d80-4342-9bd6-361cf4dd9dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time'])[1]/following::span[1]</value>
      <webElementGuid>0ef71cc0-6ea3-4da5-832a-718fefbcef51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250'])[1]/following::span[4]</value>
      <webElementGuid>86b16a87-f281-4c8f-ac5c-c548a7f7d369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Vehicle Service Protection summary.'])[1]/preceding::span[1]</value>
      <webElementGuid>98654b8e-12e8-468e-ab47-26e7ff914dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/preceding::span[1]</value>
      <webElementGuid>0aac101c-18ed-41bb-9789-dfe1a140eaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Installments']/parent::*</value>
      <webElementGuid>df25bd3f-9807-4c6c-9f3b-c632c8bc63a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label[2]/span</value>
      <webElementGuid>c131262d-19c2-42f3-ab7c-014c08eb80f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Installments' or . = 'Installments')]</value>
      <webElementGuid>0b9d5a05-7ee0-4a6c-80c2-1a00e8454301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
