<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Explore additional benefits_c-accordio_2dc32c</name>
   <tag></tag>
   <elementGuidId>6c6e3925-738b-4c03-9c63-1c5558863db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.c-accordion__title-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/section[4]/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3cc878cf-d790-46a5-a859-62adee51a058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-accordion__title-icon</value>
      <webElementGuid>55439c43-a6c6-42f1-86a6-0bd46a74ac47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;c-accordion js-accordion&quot;]/div[@class=&quot;c-accordion__header js-accordion__title&quot;]/span[@class=&quot;c-accordion__title-icon&quot;]</value>
      <webElementGuid>9808ba44-2c2c-4007-89ca-d6493612896a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/section[4]/div/div/div/div/span</value>
      <webElementGuid>3b08670c-2a52-4ac1-badf-55920f5c52f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/div/div/span</value>
      <webElementGuid>9a603bc8-a9d6-404e-89f1-ab4f49413cd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
