<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Where can I have my vehicle repaired</name>
   <tag></tag>
   <elementGuidId>4a0ad224-cc0c-43c6-9a46-40db407e2138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faq-button-1 > span.mb-0 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-1']/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8039989a-edbf-4607-893b-22d717c55b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Where can I have my vehicle repaired?  </value>
      <webElementGuid>10dddf7a-691c-4af8-890c-6acce38e9bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-1&quot;)/span[@class=&quot;mb-0&quot;]/div[1]</value>
      <webElementGuid>ea9ecae8-f14e-4f30-a9f2-35890f0d238b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-1']/span/div</value>
      <webElementGuid>afa4064d-334b-4ecd-8b30-67e295552ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What if my vehicle is still under warranty?'])[1]/following::div[6]</value>
      <webElementGuid>4f756e7d-1bfa-4a50-b57d-cd3814829422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have questions about One Protect VSP?'])[1]/following::div[15]</value>
      <webElementGuid>79ec57ca-62b3-4f1e-adc5-247e7061a57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='claims help page'])[1]/preceding::div[1]</value>
      <webElementGuid>27843122-fd95-4c08-9f15-be069917eabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[2]/div/mdb-accordion-item-head/div/a/span/div</value>
      <webElementGuid>83617d1c-1329-4820-801b-a81db7676250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Where can I have my vehicle repaired?  ' or . = 'Where can I have my vehicle repaired?  ')]</value>
      <webElementGuid>2f80d3b4-2939-43d0-a9a5-ded1ebcadd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
