<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_What is included with Roadside Assistance</name>
   <tag></tag>
   <elementGuidId>aaff6ebf-bf93-4d48-a100-885780b8e359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdb-accordion-head-901</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mdb-accordion-head-901']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73a5e078-38e1-4f45-a912-549ffc62edf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>6c7b9ffe-b570-4a09-bebf-97a38b62a5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdb-accordion-head-901</value>
      <webElementGuid>1d99790c-1854-41ed-8bba-56ac5a89cfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What is included with Roadside Assistance? </value>
      <webElementGuid>7d026826-9ad4-4543-8a4c-de21b9149032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdb-accordion-head-901&quot;)</value>
      <webElementGuid>fa1d2ede-a7d4-48a0-b1ab-5143130bada6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mdb-accordion-head-901']</value>
      <webElementGuid>0aa96d3d-012a-436f-bc8d-3776abf23b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[3]/div/app-slice-faq/div/div[2]/div/div/div/div/mdb-accordion/div/mdb-accordion-item[6]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>8dae1cd4-890b-42ca-a470-50e55ada0563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Agreement'])[2]/following::div[2]</value>
      <webElementGuid>08958596-1e69-440d-8bd5-840697ba5932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is not covered?'])[1]/following::div[5]</value>
      <webElementGuid>c2700146-d7c3-41dc-8f79-40436cd769d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdb-accordion-item[6]/div/mdb-accordion-item-head/div</value>
      <webElementGuid>a317210f-2f1a-4301-99c2-de4cf09736a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mdb-accordion-head-901' and (text() = 'What is included with Roadside Assistance? ' or . = 'What is included with Roadside Assistance? ')]</value>
      <webElementGuid>fe2c5ac4-c378-403d-9c09-842a11ec70c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
