<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_What if my vehicle is still under warrant_d30b4f</name>
   <tag></tag>
   <elementGuidId>56c8dd7b-ef80-4638-9f5d-14201c12c3a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdb-accordion-indicator.rotate-icon.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='faq-button-0']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4e1853f8-ddff-44ee-8b81-bd9da236b09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>986434b1-fefa-46ae-9889-7dc1cdfde5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdb-accordion-indicator rotate-icon ng-star-inserted</value>
      <webElementGuid>1f856a8a-6413-40df-8b3d-64d4f3ec9af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faq-button-0&quot;)/i[@class=&quot;mdb-accordion-indicator rotate-icon ng-star-inserted&quot;]</value>
      <webElementGuid>2eb33366-78b3-4cee-a29c-c5817ef8e947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='faq-button-0']/i</value>
      <webElementGuid>fe104695-1c54-4e2e-8eee-3050374d5fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>4c1f72d7-63d7-45ab-925e-ca07f2856cec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
