<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Silver</name>
   <tag></tag>
   <elementGuidId>2a88232b-6942-4bb7-9323-b4c4136fbe95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chose-plan-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c15a4f31-cae9-4231-b2a8-5ec544b2ecbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>39f40190-e0a9-43fe-a1d0-15047c4a91e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plan-select ng-star-inserted</value>
      <webElementGuid>f794bd8b-c30b-4e2a-be63-b14459de813b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chose-plan-1</value>
      <webElementGuid>e975d563-2959-447b-8ba0-ef00fa9de15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silver</value>
      <webElementGuid>e7256fa0-26fc-4379-bc12-247241561239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-1&quot;)</value>
      <webElementGuid>92bc4b20-eb46-4586-8ffb-b002a786082d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-1']</value>
      <webElementGuid>c42c3c35-a263-4fc0-b73a-25f6ef79c571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[2]/div/app-slice-product-tabset/div/div/app-plan-select/div/div/div/div/div/div[2]</value>
      <webElementGuid>93672c17-7867-4ff4-8821-b99469f1902f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powertrain'])[1]/following::div[1]</value>
      <webElementGuid>0db18397-ca78-4933-8b59-a9772b2784e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********000098'])[1]/following::div[18]</value>
      <webElementGuid>0dfc0a17-7ae4-4f99-bf13-7020399de4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/preceding::div[2]</value>
      <webElementGuid>c5c1d1f5-c6a9-459f-a0ed-54c8a640c6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]</value>
      <webElementGuid>63668844-5cb9-4ff7-b66a-3bf98856ec61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chose-plan-1' and (text() = 'Silver' or . = 'Silver')]</value>
      <webElementGuid>1fcebf4d-658a-4a15-b462-3d8d7c3688a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
