<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms and Conditions</name>
   <tag></tag>
   <elementGuidId>bfb70b05-b9b5-445f-872e-0d6d59b386e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4 > a.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13c4662e-932c-4767-9277-dd70cbe0c2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c64de9e-02ff-40ff-b878-8de1b006440b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>5ad63bb0-8fd7-4843-9f4b-c6d85b94239c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>eeab6a93-1810-44cc-a724-f9493229614e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Terms and Conditions (opens in a new tab)</value>
      <webElementGuid>a826848c-a14c-439a-9ccf-da8cd21990e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/legal/terms-and-conditions</value>
      <webElementGuid>9f913395-147e-4c83-849e-0f07003eb3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/legal/terms-and-conditions</value>
      <webElementGuid>676e8bd7-c54a-4770-bd76-4d180cf82c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>e8bda23d-cf66-4042-86cb-90f9f39ccfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms and Conditions</value>
      <webElementGuid>05849e0e-993b-49b3-a350-786d94bdbda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c157-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-footer[@class=&quot;ng-tns-c157-0&quot;]/app-footer-contact-us[@class=&quot;ng-star-inserted&quot;]/footer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;footer-copyright text-center p-4&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-8 row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>0d54508f-7a46-4871-9fec-e685d16cd7d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      <webElementGuid>d3e8007c-4302-488d-831c-fe0513f39ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms and Conditions')]</value>
      <webElementGuid>9989dfe5-d71f-4816-9171-d2fcad3b20f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sales@oneprotectplans.com'])[1]/following::a[1]</value>
      <webElementGuid>bcba9210-d755-4b68-8ea2-1afc6f371112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(833) 954-0085'])[3]/following::a[1]</value>
      <webElementGuid>afc08924-df4e-42ed-ab51-ee9ab057cd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::a[1]</value>
      <webElementGuid>b552a83b-91ca-4875-8d8b-6de448511a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::a[2]</value>
      <webElementGuid>1238a9f5-4161-42ef-8dae-d49143cdd8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terms and Conditions']/parent::*</value>
      <webElementGuid>80445f35-4f26-4ab2-84c9-09110470f772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/legal/terms-and-conditions')]</value>
      <webElementGuid>43e115ea-f461-49f0-8724-dab58f540a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>eaeb91ef-4b51-4ffb-811c-462d6019b40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/legal/terms-and-conditions' and (text() = 'Terms and Conditions' or . = 'Terms and Conditions')]</value>
      <webElementGuid>fcc1e329-965f-4b8e-b5ef-2886041e9881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
