<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_(833) 954-0085_fa-times fas</name>
   <tag></tag>
   <elementGuidId>358a0aa5-2cd2-4ec4-8d1c-8c0929af74c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-times.fas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='phoneModal']/div/div/div/button/mdb-icon/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cdffc92d-d5e8-41f8-a2e3-06497ac373ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-times fas</value>
      <webElementGuid>22f42c6a-c635-4bfe-94f1-860cc27206a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneModal&quot;)/div[@class=&quot;modal-dialog modal-side modal-bottom-right modal-notify modal-info phone-modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/button[@class=&quot;close&quot;]/mdb-icon[@class=&quot;fas&quot;]/i[@class=&quot;fa-times fas&quot;]</value>
      <webElementGuid>b7549801-9fc9-4336-a44b-6c697bf50aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='phoneModal']/div/div/div/button/mdb-icon/i</value>
      <webElementGuid>c00b9c98-dc4b-4bad-a75d-ad29d5e8cf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>569bafc4-c6d4-4d20-a175-65f4a56adafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
