<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dealership ID_dealershipId</name>
   <tag></tag>
   <elementGuidId>a5d60aa0-bb27-4f72-bdd6-00f00d6cb396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dealershipId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dealershipId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2e64aa8-2f49-4d8a-9c37-b4906366fc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>dealerlabel</value>
      <webElementGuid>cfa71492-5b97-4eac-80a2-cf1b6eaf21d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd4b9e07-7139-451a-8407-a671a89b7cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dealershipId</value>
      <webElementGuid>be848623-4202-4366-b92b-65c9d90af74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dealershipId</value>
      <webElementGuid>9c3aecf3-2804-4e7e-8e09-f8944c2e8123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>4091e232-731f-4157-9bb9-e608950538a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1f8fe752-977a-414b-93c7-d36f509092a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealershipId&quot;)</value>
      <webElementGuid>1597ab37-9bb9-4c46-8fe9-97557fdcc814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dealershipId']</value>
      <webElementGuid>48dcf393-f322-471d-9a2e-11aa39858fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div/div/app-slice-content-block/div/section/div/div/div/div/app-service-drive/div/div/form/div/input</value>
      <webElementGuid>d644c5d6-d236-42ce-a0bb-4c466a68de32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6f1166f3-7a5c-47d4-bcc9-4a1e26beb2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dealershipId']</value>
      <webElementGuid>9813c479-2e4f-49a3-ac02-b10934902b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
