<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms and Conditions</name>
   <tag></tag>
   <elementGuidId>8580ec5a-4d6f-4e01-b004-316bdae6aa85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4 > a.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11e647c2-c97b-46f1-b697-8a28b377e183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>639f9b1e-231d-42eb-83f9-283aa41e8cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>00607fb4-21b5-4281-a60c-8192a11e5a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>80725b2b-86b1-4d9c-8d52-766fb7920b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Terms and Conditions (opens in a new tab)</value>
      <webElementGuid>3e7ab002-7f67-4454-ab10-67939c3aa0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/legal/terms-and-conditions</value>
      <webElementGuid>baabaa74-5a16-4428-bb25-ba02d00338d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/legal/terms-and-conditions</value>
      <webElementGuid>bf2a3393-0fdb-4296-bdcd-5fbbfe2fd864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>2b43a1f7-42e4-4d52-a063-39c80ef9c192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms and Conditions</value>
      <webElementGuid>4963eb5d-9a4e-4238-8e69-110abd30115b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;container-fluid h-100 ng-tns-c157-0 ng-trigger ng-trigger-fadeAnimation&quot;]/app-footer[@class=&quot;ng-tns-c157-0&quot;]/app-footer-contact-us[@class=&quot;ng-star-inserted&quot;]/footer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;footer-copyright text-center p-4&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-8 row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>aad578e7-5fa0-403f-9d4c-2d4db8dbc73d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-footer/app-footer-contact-us/footer/div[2]/div/div[2]/div/a</value>
      <webElementGuid>d63658f9-2f6a-4a7a-9f10-89dda8cf3cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms and Conditions')]</value>
      <webElementGuid>333158fa-9266-41ef-85d2-9b88f4d04381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@vroomprotect.com'])[1]/following::a[1]</value>
      <webElementGuid>3007e4cb-38ce-448e-8634-8ebf1d1aa96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(833) 951-0123'])[3]/following::a[1]</value>
      <webElementGuid>ddb46913-d413-476b-bbbd-0fcac6dc82aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::a[1]</value>
      <webElementGuid>aea28124-fabb-4f43-a6b9-74f0be4c91ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessibility'])[1]/preceding::a[2]</value>
      <webElementGuid>8ff44293-2f21-4c65-8a87-b151d0fea42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terms and Conditions']/parent::*</value>
      <webElementGuid>1156e266-e1f2-4802-b815-92509004616b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/legal/terms-and-conditions')]</value>
      <webElementGuid>62904af9-ae9b-4f50-be97-470869fd93f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>f75e1f90-89b0-449a-b430-9c40e8d6e694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/legal/terms-and-conditions' and (text() = 'Terms and Conditions' or . = 'Terms and Conditions')]</value>
      <webElementGuid>ed8d1474-3f2d-48b7-86fd-8475cc3312b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
