<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_COMPLETE</name>
   <tag></tag>
   <elementGuidId>83f7433c-57fd-4e77-849f-a62f78ed0735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-verification-complete-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='address-verification-complete-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73f46b4f-a7d4-49f4-a6a2-2548afbf2896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-verification-complete-btn</value>
      <webElementGuid>ba2427e4-a0eb-443e-abd3-c18afd991655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ff29d9e7-5503-4d95-a6db-2c4a3582fdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn waves-light</value>
      <webElementGuid>cf3b08fd-313c-4ebf-91aa-d3b05e494044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COMPLETE</value>
      <webElementGuid>3187647f-cc18-43bc-bedc-5995fa347ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-verification-complete-btn&quot;)</value>
      <webElementGuid>1b14ba4b-affe-42a4-b47f-8d49fdf51bb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='address-verification-complete-btn']</value>
      <webElementGuid>4a382c37-fe97-4893-9576-35172abc2a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::button[1]</value>
      <webElementGuid>91aa82b0-9af9-48c2-a2c8-0ec74def4818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Verification'])[1]/following::button[1]</value>
      <webElementGuid>19d0c835-0742-4430-a221-b7cb6b2e44ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COMPLETE']/parent::*</value>
      <webElementGuid>da0db869-028c-4516-9d54-1c64290de774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>a9df905d-c64f-4780-92c9-f2c23b288e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'address-verification-complete-btn' and @type = 'submit' and (text() = 'COMPLETE' or . = 'COMPLETE')]</value>
      <webElementGuid>2a8bceee-6e5b-4a53-b854-91826c4c0a63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
