<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue to Review</name>
   <tag></tag>
   <elementGuidId>ddced262-3595-42d8-9d21-3e78d0cfda35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continue-to-review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='continue-to-review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57aa6369-6f2c-4fd7-87b5-4eccb5331a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>178dc844-f841-4dcd-b6e2-370f2e182b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continue-to-review</value>
      <webElementGuid>2c3b6f47-5e35-4377-b9d3-952021146ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn waves-light float-right</value>
      <webElementGuid>d39595c0-d6e4-4582-9985-328ea888eb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue to Review </value>
      <webElementGuid>5cc25736-c225-4482-bc8b-822ca10e53d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continue-to-review&quot;)</value>
      <webElementGuid>73a17cb0-bc66-4cc8-a1b5-e468aa912480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='continue-to-review']</value>
      <webElementGuid>dac548f0-5938-48be-88f8-2e77fbe6a790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[6]/button</value>
      <webElementGuid>35a794dc-6013-4da4-a360-16fd5b0a5b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip code'])[1]/following::button[1]</value>
      <webElementGuid>4f23a7d5-6a21-429f-b3ed-87a9868b3853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::button[1]</value>
      <webElementGuid>629cac57-78c2-4af5-a0ac-6e646773cd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::button[1]</value>
      <webElementGuid>8400ede8-0470-41d2-8a92-5ff03d4ca630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROTECTION FOR THE FOLLOWING VEHICLE:'])[1]/preceding::button[1]</value>
      <webElementGuid>5ec6a1bd-7cd9-4b47-b8f3-71046322753a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue to Review']/parent::*</value>
      <webElementGuid>35602f64-7d39-47ef-bbf5-c02d7dfd1d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>9c267510-2325-4a3c-87f7-cbcfc0a2223a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'continue-to-review' and (text() = ' Continue to Review ' or . = ' Continue to Review ')]</value>
      <webElementGuid>a79cd075-e302-4438-b5a6-c182d68c239a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
