<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platinum</name>
   <tag></tag>
   <elementGuidId>1d650619-8ee3-4116-b0f2-50bf1b6cecd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-0 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chose-plan-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d66a5a85-22ac-47d8-b5a7-08213cef97d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platinum</value>
      <webElementGuid>0a7c6594-7c2b-4f6a-9ba7-5d5b8d8b1d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-0&quot;)/div[1]</value>
      <webElementGuid>88997710-a9b3-4c9c-b728-eb9744bf8b54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-0']/div</value>
      <webElementGuid>1949754b-400a-4976-9ab2-803c6ea667e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********020470'])[1]/following::div[17]</value>
      <webElementGuid>a62fb8a1-9412-491c-a012-df20726be93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A4'])[1]/following::div[18]</value>
      <webElementGuid>58ee14f3-9792-4dd0-928f-8e1aa9d1b470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Powertrain+'])[1]/preceding::div[1]</value>
      <webElementGuid>c44948c1-45c6-4d63-9d7f-e820c1c85d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platinum']/parent::*</value>
      <webElementGuid>46aa217b-0c99-4b1c-995f-0a7e4512e277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>c2e6c799-38a9-4404-a7cc-99a41f02095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Platinum' or . = 'Platinum')]</value>
      <webElementGuid>f5ee7474-5b7e-44ae-94aa-32e698b0b683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
