<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Powertrain</name>
   <tag></tag>
   <elementGuidId>b9adfeec-cff7-470a-8f5c-e2ee804abf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chose-plan-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;chose-plan-2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bfc7d96b-861a-44d1-a7f9-6cf314bd5a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c012c967-5649-4536-86c7-2d1c0436955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plan-select ng-star-inserted</value>
      <webElementGuid>015279ce-85b5-40fe-b66c-a0e371121739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chose-plan-1</value>
      <webElementGuid>639dee25-a361-45c4-b240-fb0c9e30cef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Powertrain+</value>
      <webElementGuid>a2acc971-1b88-426a-829c-2d050053979d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chose-plan-1&quot;)</value>
      <webElementGuid>cc1c8cb4-82c6-4d4a-93df-657f2dcbd2b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chose-plan-1']</value>
      <webElementGuid>881b281b-e0c5-4765-9ed5-26847cd83f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-product-home/div/div[2]/div/app-slice-product-tabset/div/div/app-plan-select/div/div/div/div/div/div[2]</value>
      <webElementGuid>586646e9-8771-4025-8407-3c64ee0453c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platinum'])[1]/following::div[1]</value>
      <webElementGuid>38520ed1-fa0f-4155-bcd8-454e278fdba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN ***********020470'])[1]/following::div[18]</value>
      <webElementGuid>2d1e5bb2-1ee1-43cc-be91-3128fecb6660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]</value>
      <webElementGuid>d2384ed1-f6d4-43ce-a68a-b9b790ac65ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chose-plan-1' and (text() = 'Powertrain+' or . = 'Powertrain+')]</value>
      <webElementGuid>328e4467-be37-4a08-8ee1-e42e4bbb7d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
