<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ConfirmEmail</name>
   <tag></tag>
   <elementGuidId>63d9f982-315e-49a0-982f-69da0157777c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailFormConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailFormConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a2fb7d3-cb94-4c44-9f16-a6f2893bbac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b1df9fcc-3382-411a-a8dc-a5173ca20ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailFormConfirm</value>
      <webElementGuid>7e1f5a9b-31a0-4c6e-9d75-cd0e7caad5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>7bfe0235-5b56-4dc1-9dc3-4f08f834fb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-tns-c169-9 validate-success validate-error ng-untouched ng-invalid ng-dirty</value>
      <webElementGuid>669162c0-151d-421b-b808-ead556c90b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailFormConfirm&quot;)</value>
      <webElementGuid>4fe073d7-cad4-4f31-b187-4b95f28ab7f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailFormConfirm']</value>
      <webElementGuid>a84e1585-33ce-40c0-ac64-8b82a7a03069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-contact-information/mdb-card/mdb-card-body/form/div[3]/div/div/input</value>
      <webElementGuid>439fde29-3fba-4cd7-b4ff-3dde58b0b31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>54c31232-21d4-4529-a85b-e1c5132967df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailFormConfirm']</value>
      <webElementGuid>8f577994-4234-47f1-b729-10c85f5b23b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
