<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number</name>
   <tag></tag>
   <elementGuidId>9909b552-de52-44a2-9ca6-cfcdf93d7922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingFormCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingFormCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b7debf6-ba96-4b48-8ace-b45deaec1602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28ef5f5c-d3ac-4013-a866-8abe1afd5ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingFormCardNumber</value>
      <webElementGuid>a7c221eb-345d-475f-8f44-99d71b2249bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>f8908a94-4a6c-430c-a728-f4ed2af62137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide validate-success validate-error ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a9b149bd-d6f4-45e4-89bf-6ca88dcaee76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingFormCardNumber&quot;)</value>
      <webElementGuid>222573cc-1069-489d-91b7-4e05de5e1540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingFormCardNumber']</value>
      <webElementGuid>a6a65bad-6dfe-4371-b459-453eb7a9e2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[2]/div/div/input</value>
      <webElementGuid>af085321-0029-4e67-86af-8cc2977d9a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>352ea09a-e090-44d6-9595-b5bbbc0fe771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingFormCardNumber']</value>
      <webElementGuid>af6650bf-c596-4d06-a63d-117011edc9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
