<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month</name>
   <tag></tag>
   <elementGuidId>dcb822bf-9454-4b18-a208-dbf775323a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expoDateMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='expoDateMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e0e193d-e334-4dd8-bb08-f5fdc1419ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>90acadbb-7977-4805-b7cf-54de76b0f266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expoDateMonth</value>
      <webElementGuid>168ac8c9-828a-45b3-acf4-fc2d4ffe6b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Exp Month *</value>
      <webElementGuid>56d4f844-08b9-4007-9a09-efbd64e6edf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expirationMonth</value>
      <webElementGuid>4248fc34-d002-46c2-be38-0c2d20678a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lp-hide ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9caa1b4f-6a36-4aee-8ef3-f47d7fa7d088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  January February March April May June July August September October November December</value>
      <webElementGuid>7de936b8-7b35-4c29-80d6-2c358d115f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expoDateMonth&quot;)</value>
      <webElementGuid>a12edb22-b57f-4f78-aa5f-4fbf0d42c632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='expoDateMonth']</value>
      <webElementGuid>278d0410-a370-4f63-857c-34a9440781c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/div/app-checkout/div/div[3]/div/app-checkout-billing-information/mdb-card/mdb-card-body/form/div[3]/div/div/select</value>
      <webElementGuid>3c1909fc-4271-4591-a153-dd730284bd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exp Month'])[1]/following::select[1]</value>
      <webElementGuid>bbd823b3-2e8f-4827-92ed-e943cc13c1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[1]/following::select[1]</value>
      <webElementGuid>c8d6d9c8-a2de-4672-9be7-f7f5d6806fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Year'])[1]/preceding::select[1]</value>
      <webElementGuid>f237d58b-fed4-4243-80b9-73b163990dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVC'])[1]/preceding::select[2]</value>
      <webElementGuid>b789d08c-283f-4755-a328-c8a9ca225aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0fe2474e-a23f-4c50-b943-bb472c70b9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'expoDateMonth' and @placeholder = 'Exp Month *' and (text() = '  January February March April May June July August September October November December' or . = '  January February March April May June July August September October November December')]</value>
      <webElementGuid>39a0a98a-9235-4441-9e1b-d6205f100723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
