<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_coverage</name>
   <tag></tag>
   <elementGuidId>d83a4c4b-8b0b-4178-a00a-4c14df1dc25f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/section/div/div/div[2]/div[4]/div/div/div[2]/article/div/div/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>4728853b-b739-4110-8087-1c9f26c53b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip__text u-text-brand</value>
      <webElementGuid>b4f242c2-2356-4970-aaad-c31d203394d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec6f4769-0a13-43ec-8f7c-8e7a3a59c333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tippy-11</value>
      <webElementGuid>7215e93e-9a9c-4607-ac4c-2134bfda184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>coverage</value>
      <webElementGuid>e0aceed1-4b05-4209-a00c-742955125af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/div[@class=&quot;u-pb&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;c-accordion js-accordion&quot;]/div[@class=&quot;c-accordion__panel js-accordion__panel&quot;]/div[@class=&quot;c-accordion__content&quot;]/div[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item  u-1/2  u-1/1@s&quot;]/article[@class=&quot;c-item-teaser u-m c-item-teaser--small c-item-teaser--inline&quot;]/div[@class=&quot;c-item-teaser__body&quot;]/div[@class=&quot;c-item-teaser__text&quot;]/b[@class=&quot;tooltip__text u-text-brand&quot;]</value>
      <webElementGuid>043ba837-bbe8-4dae-9c50-5ab7c26fbe40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section/div/div/div[2]/div[4]/div/div/div[2]/article/div/div/b</value>
      <webElementGuid>39e53fc4-495b-425d-a4ee-c8e72df2565f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='like kind quality.'])[1]/following::b[1]</value>
      <webElementGuid>5cf71338-f61f-4295-bd2f-4285485ceb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Towing reimbursement of up to $100 to your nearest Audi dealer or authorized service provider.'])[1]/preceding::b[1]</value>
      <webElementGuid>053a4405-71a8-4685-ac67-c3ff320fd79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rental car reimbursement up to $35 per day for up to 10 days if required'])[1]/preceding::b[1]</value>
      <webElementGuid>c2664489-18d7-48ba-9c8c-024c341fcb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='coverage']/parent::*</value>
      <webElementGuid>d3f5c5c9-3946-4918-a4a3-5f5ac6c82348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/div/b</value>
      <webElementGuid>ed594af4-1412-42e4-892a-55029c4f7977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'coverage' or . = 'coverage')]</value>
      <webElementGuid>1a34f0af-47d0-4cc6-885c-92e98227bc30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
