<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_fuel</name>
   <tag></tag>
   <elementGuidId>39db2db2-b564-4736-b558-ddca46972127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/section/div/div/div[2]/div[4]/div/div/div/article[2]/div/div/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b.tooltip__text.u-text-brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>616de585-a65e-4e04-92a2-eb224923cadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tooltip__text u-text-brand</value>
      <webElementGuid>be7f4949-c8cd-4cfe-8bf9-e62b22ee1db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c669e5d-717d-4f2a-9713-46b3cca51977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tippy-8</value>
      <webElementGuid>3e7ec2e9-e638-4329-a9ef-8de9eb29454d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>fuel</value>
      <webElementGuid>c435a2e8-2b5b-4d25-8cb8-8ba4e2a7203f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/div[@class=&quot;u-pb&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;c-accordion js-accordion&quot;]/div[@class=&quot;c-accordion__panel js-accordion__panel&quot;]/div[@class=&quot;c-accordion__content&quot;]/div[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item  u-1/2  u-1/1@s&quot;]/article[@class=&quot;c-item-teaser u-m c-item-teaser--small c-item-teaser--inline&quot;]/div[@class=&quot;c-item-teaser__body&quot;]/div[@class=&quot;c-item-teaser__text&quot;]/b[@class=&quot;tooltip__text u-text-brand&quot;]</value>
      <webElementGuid>80e1b2a8-8994-4ba3-a98d-f5130c6c7500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section/div/div/div[2]/div[4]/div/div/div/article[2]/div/div/b</value>
      <webElementGuid>24e5f827-072a-4188-8be9-6e241c101cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See additional benefits'])[1]/following::b[1]</value>
      <webElementGuid>c0a6be38-609e-4526-aded-fbc40d64ff13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High-Tech'])[1]/following::b[1]</value>
      <webElementGuid>c9bf729d-fbd8-4682-ab65-786d86b5e60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fluid delivery'])[1]/preceding::b[1]</value>
      <webElementGuid>7435d0c3-ae5d-4ba5-9b51-5aa016644833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='fuel']/parent::*</value>
      <webElementGuid>2357de94-52c2-4740-9eb4-ece8131c5202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>051a33c1-38d8-4349-a53a-5335d9253ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'fuel' or . = 'fuel')]</value>
      <webElementGuid>fb6c3671-a86d-43e8-978b-bf299c552f5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
