<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify Email Address_verifyEmailAddress</name>
   <tag></tag>
   <elementGuidId>7ebdeb25-17e1-4c3d-ba31-e7b54d1cc8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verifyEmailAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verifyEmailAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>360ae5d7-bfbd-4745-8b5e-adab85117c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>39ebce8c-1844-4e21-9036-d805609b659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e9473b3b-7c27-4b2f-8b29-09feb0238492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verifyEmailAddress</value>
      <webElementGuid>0636fb2a-1ce3-4a80-a274-f7a0922b9f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verifyEmailAddress</value>
      <webElementGuid>b7f94f60-9aed-4f41-a414-f840679a9372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifyEmailAddress&quot;)</value>
      <webElementGuid>387f5479-0cb8-46e0-b4c4-9940c7662460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verifyEmailAddress']</value>
      <webElementGuid>0912dde6-fc71-4078-a0a5-d96128baad99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div[6]/div/div/input</value>
      <webElementGuid>d2ba75dc-ac9a-48a4-8bb5-8dbe11c17b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>e207fa5b-27de-4386-a211-8d5c7dde76c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'verifyEmailAddress' and @id = 'verifyEmailAddress']</value>
      <webElementGuid>63b49470-ea1c-4e9e-b620-127cb5ed9db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
