<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Secondary Phone Number_secondaryPhoneNumber</name>
   <tag></tag>
   <elementGuidId>5333c1a0-37b1-4843-95d7-3cb67bb5bc19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondaryPhoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#secondaryPhoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3323dfd-c2aa-4c3a-88f5-603d88d3ce1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>f9d16cbd-1491-448d-a5ff-ba383ed00d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3787accd-7292-4eee-b589-f90047eb8dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondaryPhoneNumber</value>
      <webElementGuid>3b0ba156-d17b-49e0-a771-5e93c5c99d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondaryPhoneNumber</value>
      <webElementGuid>e597aa93-cb98-43e9-84fc-6b24a6c83382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8a3879d0-6f9c-4148-abd6-da8fa5e95e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondaryPhoneNumber&quot;)</value>
      <webElementGuid>6adcc4e8-a10a-49ec-8393-4988f3e4b0a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondaryPhoneNumber']</value>
      <webElementGuid>80809808-4899-4d4a-bcc4-e04cc4071130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div[4]/div/div/input</value>
      <webElementGuid>d7415cd0-3073-4b58-ba04-956ecb1bb47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>1b20cb69-fca5-43b6-b9fe-7f4f2f67b7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'secondaryPhoneNumber' and @id = 'secondaryPhoneNumber']</value>
      <webElementGuid>d5a47c6c-c357-4127-84af-ea18be86faaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
