<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_customerFirstName</name>
   <tag></tag>
   <elementGuidId>6e865f75-011b-4928-87f9-f8bf87f1771c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customerFirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03a9da99-491c-41be-b68e-51ba5eaf7389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>c76b8deb-fbcb-4e6b-b5ca-f1f6d94b45c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f901755e-c6ed-4e0f-a796-d01bc0109a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerFirstName</value>
      <webElementGuid>6f2c605c-8c0e-44a3-ad9f-b9006a963be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerFirstName</value>
      <webElementGuid>cd36f302-ce16-431c-b978-321ec43800bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerFirstName&quot;)</value>
      <webElementGuid>842fbaac-513d-48fc-bc6e-af764258111f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerFirstName']</value>
      <webElementGuid>594910b1-a14f-41a9-a9f1-97e81df4b41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/form/div/div/fieldset/div/div/div/div/div/input</value>
      <webElementGuid>cee483e2-4024-4798-a04c-874074022f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>614a2a81-95a5-4baa-9300-9743f955609e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerFirstName' and @id = 'customerFirstName']</value>
      <webElementGuid>a4613e76-b680-4725-b759-c9fbe7ab7f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
