<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select4860728496120</name>
   <tag></tag>
   <elementGuidId>12883bdc-813c-469a-beb3-e3e2525d7c36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedTerm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedTerm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ffd2b929-7ef8-4bb8-9d8d-aa6dc8bfafb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>9526bc78-5859-4941-a02c-63e8f5c85bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedTerm</value>
      <webElementGuid>e039a962-dd37-4fe5-a0cc-143de81b919a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedTerm</value>
      <webElementGuid>16d6609d-295e-44cd-a00c-e85c2f73f421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select4860728496120</value>
      <webElementGuid>c8eb035f-f89a-4b85-a8bd-6dd7fa632d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedTerm&quot;)</value>
      <webElementGuid>da1c361d-8a59-472d-81fe-8014ddbb8418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectedTerm']</value>
      <webElementGuid>a4997ff2-ea19-45d1-a10d-03f466fb7f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>ed91f51c-20eb-49c6-8ca8-b772897edef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250'])[1]/following::select[1]</value>
      <webElementGuid>f39ee76e-3aca-4a45-8fa3-93db7d3b0a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[1]/following::select[1]</value>
      <webElementGuid>793aa5d1-e343-405c-80aa-5990cd0d2f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time'])[1]/preceding::select[2]</value>
      <webElementGuid>6a372734-b40d-46ec-a9d1-e940d3e9b95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installments'])[1]/preceding::select[2]</value>
      <webElementGuid>9ddd6f4f-014e-40d1-9ff9-c83f26539d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b13b4a63-fa51-4320-8523-4d0784cd0b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'selectedTerm' and @id = 'selectedTerm' and (text() = 'Please select4860728496120' or . = 'Please select4860728496120')]</value>
      <webElementGuid>5f314496-8edb-43a1-b256-610b14f8a212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
