<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select100,000</name>
   <tag></tag>
   <elementGuidId>250fbc53-7e8c-42c9-844c-4dfd6ad7e77e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectedTermMileage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedTermMileage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0aa2be93-0df5-464b-8fbe-3c4fc1c99996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-input__input </value>
      <webElementGuid>bc1fe57e-b829-4147-b392-46579d86952e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedTermMileage</value>
      <webElementGuid>9bdc03e7-af5f-4178-984a-aec2a046474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedTermMileage</value>
      <webElementGuid>8deaebcd-9976-4864-9bd0-82efd83b11d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select100,000</value>
      <webElementGuid>134a665e-333a-4e2b-862d-f213c48441ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedTermMileage&quot;)</value>
      <webElementGuid>551571bf-afa8-49f9-ad8e-9f03f25cda84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectedTermMileage']</value>
      <webElementGuid>18273708-1f82-406a-9ab1-9676838fa3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section[2]/div/div/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>eb67445c-eae3-43e5-9088-f3d5e3d6eef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250'])[1]/following::select[2]</value>
      <webElementGuid>7a9e7848-6e1b-493e-9699-db77f80f4229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[1]/following::select[2]</value>
      <webElementGuid>427a4515-ed14-40f1-8a6e-260dd801f07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time'])[1]/preceding::select[1]</value>
      <webElementGuid>4d7beaae-38df-4dad-b89e-fa4abe5c807f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installments'])[1]/preceding::select[1]</value>
      <webElementGuid>78183577-3da0-4ecf-bca4-894242010573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>b9794173-ef14-498e-9f61-5afdbd66fd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'selectedTermMileage' and @id = 'selectedTermMileage' and (text() = 'Please select100,000' or . = 'Please select100,000')]</value>
      <webElementGuid>0fe272cc-1c3a-4e62-9ff0-a400ad2bd085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
