<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Explore additional benefits_c-accordio_2dc32c_1</name>
   <tag></tag>
   <elementGuidId>80f1898c-3202-49ea-978b-ae8b5ce28f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/section[4]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.c-accordion__title-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c1beb4ba-f350-4bd4-97ab-7668c268fd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-accordion__title-icon</value>
      <webElementGuid>a8aa9d00-9f19-47fb-997e-cc3a727a00c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;c-accordion js-accordion&quot;]/div[@class=&quot;c-accordion__header js-accordion__title is-active&quot;]/span[@class=&quot;c-accordion__title-icon&quot;]</value>
      <webElementGuid>b6729d02-ebca-4faa-a547-65e2f1a34424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/section[4]/div/div/div/div/span</value>
      <webElementGuid>9c9bb0b3-dd80-443b-becd-a1773ddf8ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/div/div/span</value>
      <webElementGuid>d862df3e-293a-4f43-8270-8059aeb02292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
