<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Powertrain_c-accordion__title-icon_1</name>
   <tag></tag>
   <elementGuidId>aa29ec59-c368-4f6f-b9d7-626e9c8f0469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/section/div/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.c-accordion__title-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>76c8c442-9d9a-43d2-b9dd-16a0f5cd234a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-accordion__title-icon</value>
      <webElementGuid>3d4394e0-f851-40cf-b9eb-109aef1b9f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;o-root&quot;]/main[@class=&quot;o-main&quot;]/div[@class=&quot;u-pb&quot;]/section[@class=&quot;o-content-section&quot;]/div[@class=&quot;o-page-wrap  o-page-wrap--medium&quot;]/div[@class=&quot;o-component-wrapper&quot;]/div[@class=&quot;c-accordion js-accordion&quot;]/div[@class=&quot;c-accordion__header js-accordion__title is-active&quot;]/span[@class=&quot;c-accordion__title-icon&quot;]</value>
      <webElementGuid>0d7965de-b6fa-42bf-baa1-aee270da26e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/section/div/div/div[2]/div/span</value>
      <webElementGuid>20beac2d-4bc1-4f2c-8225-74862535d5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>f0d9374d-210c-456b-8c8d-cfce83c810de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
