<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_0065500000MRMM8AAP</name>
   <tag></tag>
   <elementGuidId>3f59a070-5249-407f-998c-2a37bea3a271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='query_results']/tbody/tr[2]/td[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aebb9050-5940-4d53-a9ac-842ae24ee308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>retrieve.php?id=0065500000MRMM8AAP</value>
      <webElementGuid>c09bef7f-9591-4995-a26f-315c6dbfee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>Tip('Choose an action:&lt;br/>&lt;a href=\'update.php?sourceType=singleRecord&amp;id=0065500000MRMM8AAP\'>Update&lt;/a>  &lt;a href=\'delete.php?sourceType=singleRecord&amp;id=0065500000MRMM8AAP\'>Delete&lt;/a>  &lt;a href=\'undelete.php?sourceType=singleRecord&amp;id=0065500000MRMM8AAP\'>Undelete&lt;/a>  &lt;a href=\'purge.php?sourceType=singleRecord&amp;id=0065500000MRMM8AAP\'>Purge&lt;/a>  &lt;a href=\'jumpToSfdc.php?startUrl=0065500000MRMM8AAP\' target=\'sfdcUi\' >View in Salesforce&lt;/a>  ', STICKY, true, WIDTH, 345)</value>
      <webElementGuid>76a1b857-aab8-488b-a43b-5ddc5df5079d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0065500000MRMM8AAP</value>
      <webElementGuid>f8e5ecc8-0436-4327-b830-5c72e43c16b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;query_results&quot;)/tbody[1]/tr[2]/td[8]/a[1]</value>
      <webElementGuid>7e4afcd6-8321-4f74-bc42-d4111d5c54f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='query_results']/tbody/tr[2]/td[8]/a</value>
      <webElementGuid>5a6fa312-104b-47e1-9638-c2f3bb4e242b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'0065500000MRMM8AAP')]</value>
      <webElementGuid>9ebaf527-16e3-4e0a-aba0-6564e58884d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment_Provider__c'])[1]/following::a[5]</value>
      <webElementGuid>4e30f087-d84a-4aed-a86f-941426692602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dealershipEmployeeId__c'])[1]/following::a[5]</value>
      <webElementGuid>472ae54c-56ff-4556-adee-638fbd400767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[1]/preceding::a[1]</value>
      <webElementGuid>0c009ab4-88b3-4922-81b8-0025d68b61cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[1]</value>
      <webElementGuid>72624d31-c257-45bb-8a8f-50663c41dc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0065500000MRMM8AAP']/parent::*</value>
      <webElementGuid>b57f8e3f-0525-44bb-88ba-6cfd55c6e7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'retrieve.php?id=0065500000MRMM8AAP')]</value>
      <webElementGuid>305c7b26-291f-448d-a4e9-23dcb2ee8166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>befff8b4-3370-46e4-8f57-a72dcac5ae15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'retrieve.php?id=0065500000MRMM8AAP' and (text() = '0065500000MRMM8AAP' or . = '0065500000MRMM8AAP')]</value>
      <webElementGuid>b94be3ad-c54d-4ccb-b3a2-0c81c7655f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
