<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter or modify a SOQL query below_qu_a3c1bb</name>
   <tag></tag>
   <elementGuidId>52a391e8-2d92-4dbe-85bf-919916957a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;querySubmit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='querySubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f735b67-c0b9-4d61-b97b-55213b56e271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>005c307a-3c15-46df-b851-a013e8b3611e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>querySubmit</value>
      <webElementGuid>e6358c88-cd01-4f58-970d-f40a1f1376dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableWhileAsyncLoading</value>
      <webElementGuid>21443e9a-6c02-4325-89bd-f38f0e8d1c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Query</value>
      <webElementGuid>323fd5d9-86ee-4d56-a7e9-48320317fbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return parentChildRelationshipQueryBlocker();</value>
      <webElementGuid>24587362-4ccc-4199-b2d4-95f76c5cad8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;query_form&quot;)/table[1]/tbody[1]/tr[3]/td[1]/input[@class=&quot;disableWhileAsyncLoading&quot;]</value>
      <webElementGuid>53d36428-79e8-4595-95cd-984ba533e76f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='querySubmit']</value>
      <webElementGuid>0923d55c-de4d-42f2-be4d-8bc9d58e7574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='query_form']/table/tbody/tr[3]/td/input</value>
      <webElementGuid>2e48ba10-7d91-4835-950d-9e420ae15d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>ab3c0b99-37ca-4522-a917-8880964484b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'querySubmit']</value>
      <webElementGuid>e655617b-361e-49ad-9d02-d920487903e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
